### ISSUE TITLE
when attempting to load a dashboard url with infinite scrolling disabled, content is rendered for a split second before doing a blackout

### ISSUE THREAD

**Issue by autumn876** [enchanted-sword/dashboard-unfucker#1]
title; the script manages scrolling to the next page from the main dash. after a little while the error "Unexpected Application Error!
Node.insertBefore: Child to insert before is not a child of this node" appears. There are other messages, and they all follow the trend of "lu@https://assets.tumblr.com/pop/js/modern/vendor-522962a4.js:22:97411". Not sure if this could be an asset loading error or anything else but yeah.
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/109993329/59f454f0-a28b-43f7-8fc5-d405efd57260)

**Comment by enchanted-sword** [comment]
should be fixed in the latest commit, it was an issue where the additional data after the question mark prevented the script from treating it as a /dashboard page. it now splits the string once more to eliminate tracking data from window.location.href.
