### ISSUE TITLE
Search bar is sometimes not moved

### ISSUE THREAD

**Issue by marcustyphoon** [enchanted-sword/dashboard-unfucker#10]
Apparently the search bar loads in way later than the rest of the page? No clue why; it's not like it has to get loaded from a server. But because of this, when I refresh, sometimes the search bar is still in the sidebar instead of in the header.

Could probably solve this with another waiting loop; one can do like:

```js
const waitFor = async selector => {
    let retries = 0;
    while (retries++ < 25 && !$(selector).length) {
        await new Promise(requestAnimationFrame);
    }
}
```

Or, if one wishes to have the code after using this function never run if it never finds the element in question (this code is probably slightly harder to understand to a reader not familiar with `new Promise()`):

```js
// recursive
const waitFor = (selector, retried = 0) => new Promise(resolve => {
    $(selector).length
        ? resolve()
        : retried < 25 && requestAnimationFrame(() => waitFor(selector, retried + 1));
});
```

```js
// not recursive
const waitFor = (selector) => new Promise(async resolve => {
    for (let i = 0; i < 25; i++) {
        if ($(selector).length) {
            resolve();
            break;
        }
        await new Promise(requestAnimationFrame);
    }
});
```

(I didn't test these snippets; might have typos. Also, the number 25 is completely arbitrary. I put in a counter and saw a single-digit number of `requestAnimationFrame` loops before the search bar appeared.)

**Comment by enchanted-sword** [comment]
I think I understand how it works, how would I go about implementing it?

**Comment by marcustyphoon** [comment]
Broadly speaking, I think you could either interrupt your sequential flow of code to wait:

```js
async function $unfuck () {
    /* do some things now */
    await waitFor(keyToCss("searchSidebarItem"));
    /* do some things that need to happen once the search bar exists */
}
```
or specify only a few things that need to happen on a delay:
```js
async function $unfuck () {
    /* do some things now */
    waitFor(keyToCss("searchSidebarItem")).then(() => {
        /* do some specific things that need to happen once the search bar exists */
    })
    /* do some things now */
}
```
I didn't look that closely, but assuming none of the other code depends on the position of the search element, it would probably be possible to just delay moving it!

**Comment by enchanted-sword** [comment]
I shuffled some stuff around so that it only appends the search element to the header on permalink pages, and on pages with a native search element it instead waits for the promise to resolve and then locates the search bar and inserts it after the logo element after it loads:
```js
waitFor(keyToCss("searchSidebarItem")).then(() => {
    $search = $(keyToCss("searchSidebarItem")).eq(0);
    $search.insertAfter($logo);
});
```
This way it doesn't rely on the search bar loading before adding the navigation bar to the header, and also doesn't try to append an empty string if the promise hasn't resolved yet.
