### ISSUE TITLE
Inbox nav icon missing

### ISSUE THREAD

**Issue by queenofmeans** [enchanted-sword/dashboard-unfucker#100]
When dashboard unfucker is active on my dash, the envelope icon for inbox disappears from the list of available nav icons. When everything is turned off it's still available in the vertical navigation but when the navigation is converted back to the old nav, there's only the messaging icon visible. I've tried turning off other extensions in case of conflicts but there's no change. I'm using Tampermonkey in Chrome.

![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/143542815/20a1f61b-f92a-4a7d-9d46-31948b588bd7)

**Comment by enchanted-sword** [comment]
Did you check your adblock filter? I've had a lot of people report the same issue because they had been manually blocking the explore/shop/live/etc icons with an adblock filter and when they installed the script the adblock filter started hiding the inbox instead.

**Comment by queenofmeans** [comment]
THANK YOU! The adblock was the culprit. I had turned off my other Tumblr extensions but hadn't checked the ad blocker.
