### ISSUE TITLE
Bug: Off center blog

### ISSUE THREAD

**Issue by imnotsuspiciousshh** [enchanted-sword/dashboard-unfucker#104]
**Describe the bug**
On desktop, when you go to someone's blog page, it is severely off center.

**To Reproduce**
1. Click on url of blog you want to go to
2. Open blog in new tab (Important: NOT the url that goes [blog].tumblr.com, but tumblr.com/[blog])
3. See error

**Screenshots**
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/132789054/429c76cf-596b-45f5-9d26-229e93b5d151)

**Version**
 - 4.0.4beta

**Comment by enchanted-sword** [comment]
Can't reproduce this, I'm assuming this is because of content positioning because I only just now added a check to not apply it on permalink pages.
