### ISSUE TITLE
Page turns fully white wið extension on

### ISSUE THREAD

**Issue by K-l6408** [enchanted-sword/dashboard-unfucker#106]
**Describe the bug**
When i try to open Tumblr wið ðe extension on, ðe whole page gets deleted

**To Reproduce**
- open tumblr wið extension on 
- oh wait you can't

**Version (please complete the following information):**
- Browser: Firefox 117.0-2
- Version 4.2.2b

**Comment by enchanted-sword** [comment]
Try updating to the [latest version](https://github.com/enchanted-sword/dashboard-unfucker#installation).

**Comment by K-l6408** [comment]
Fixed, þank you!
