### ISSUE TITLE
dashboard suddenly in panorama view with ublock origin turned on

### ISSUE THREAD

**Issue by sk0gsla** [enchanted-sword/dashboard-unfucker#108]
as of this afternoon (09/01) the dashboard is displaying in panorama view (?), but only with ublock origin turned on. if ublock is turned off the dashboard reverts to normal width.

**screenshots**
(ublock off)
<img width="1381" alt="ublock off" src="https://github.com/enchanted-sword/dashboard-unfucker/assets/143856554/f72b281b-6940-42aa-9f87-dcddbd6b0bc2">
(ublock on)
<img width="1377" alt="ublock on" src="https://github.com/enchanted-sword/dashboard-unfucker/assets/143856554/640535df-d72f-4fbb-ae9b-456f043203c3">

**version**
 - firefox 116.0.2
 - ublock 1.51.0
 - unfucker 4.1.3

**Comment by sk0gsla** [comment]
reinstalled unfucker and reset ublock settings for tumblr and it seems to be fixed! disregard <3

**Comment by barlowgirl13** [comment]
I am also having this issue and I've uninstalled and reinstalled. Turning off ublock origin doesn't fix it.
