### ISSUE TITLE
Double UI on new page open.

### ISSUE THREAD

**Issue by TheGeniusIdiotAndStickMerchant** [enchanted-sword/dashboard-unfucker#109]
**Describe the bug**
When I open a new tab, and then Tumblr, I get two copies of the dashboard unfucker v4.1.3 text, with dots and gear next to it. Clicking on either has no effect, reloading solves it.

**To Reproduce**
1. Open a new tab.
2. Type in tumblr.com

**Screenshots**
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/136821116/a0d578df-a5cd-4433-a242-a11be38de559)

**Version (please complete the following information):**
 - Browser: Google Chrome116.0.5845.141
 - Version: v4.1.3

**Comment by enchanted-sword** [comment]
Not sure what would cause this, I haven't seen a "multiple injection" glitch since before v4.0.0, but I added a failsafe for this in the latest update anyways.
