### ISSUE TITLE
Dashboard in panorama view

### ISSUE THREAD

**Issue by barlowgirl13** [enchanted-sword/dashboard-unfucker#111]
Today or maybe late last night, my dashboard is sized weirdly when using unfucker. I checked if it was other extensions but it still happens when they're turned off. I also tried turning off basically all the options and that didn't change anything. I uninstalled and reinstalled and it didn't fix it.

With tampermonkey turned off:

![tumblr 1](https://github.com/enchanted-sword/dashboard-unfucker/assets/65017840/a51c3a32-a40d-432a-8636-b8f8af885ab9)

With tampermonkey turned on:

![tumblr 2](https://github.com/enchanted-sword/dashboard-unfucker/assets/65017840/1ea2c994-d376-42da-99bd-382fabe60735)

With tampermonkey on, but the dash in full screen (I normally use tumblr with the window half-sized, but it only changed today):

![tumblr 3](https://github.com/enchanted-sword/dashboard-unfucker/assets/65017840/ee6b4616-a53d-4a2d-9b45-a760d51d77fa)

 - chrome 116.0.5845.141
 - Version 4.2.1

**Comment by barlowgirl13** [comment]
Tried violentmonkey instead, didn't help.

**Comment by enchanted-sword** [comment]
That's because you're using the narrower "mobile" layout. The fullscreen layout in the picture you sent is the normal width. The script is written for the desktop layout.

**Comment by barlowgirl13** [comment]
It literally worked until today though??? Like I was using it for weeks and it was fine.
