### ISSUE TITLE
Not all parts of the dashboard unfucker consistently load

### ISSUE THREAD

**Issue by ChangelingRain** [enchanted-sword/dashboard-unfucker#112]
**Describe the bug**
Various features of the dashboard unfucker do not consistently load when the page is loaded, requiring a refresh to activate the nonfunctional feature. 

**To Reproduce**
1. Unknown. Observed issues include:
2. 'Account' menu silently does not generate, and clicking on the account button ![](https://i.imgur.com/sutAjxE.png) will produce no menu. Refreshing fixes.
3. Opening a the queue, or a post in the on-dash post format(tumblr.com/[user]/[post#]), occasionally does not apply the reverted activity feed redesign. Refreshing fixes.

**Screenshots**
I don't have a screenshot of the account menu not generating, but here's a post in the on-dash post format not applying the redesign;
![](https://i.imgur.com/ypACQkS.png)
And the associated console logs(though they don't seem very helpful)
![](https://i.imgur.com/CoUlFad.png)

**Version (please complete the following information):**
 - Firefox 108.0.2 (32-bit) 
 - unfucker version 4.2.1

**Additional context**
Yeah sorry about this low-information report, if there are specific screenshots or console data that could help I can get it if and/or when these happen again

**Comment by enchanted-sword** [comment]
Not sure why the account button fails to load, the script doesn't modify it. As for the queue, are you opening it in a new tab? I haven't been able to replicate it consistently but there is a known issue where the script won't lpad properly in background tabs.

**Comment by ChangelingRain** [comment]
Yeah, I am opening it in a new tab(middle click) which doesn't immediately take focus, so it's probably that then

**Comment by enchanted-sword** [comment]
Should be fixed in v4.3.0.

**Comment by ChangelingRain** [comment]
Yup, seems to be!
