### ISSUE TITLE
Unfucker not installing?

### ISSUE THREAD

**Issue by nogsmcgogs** [enchanted-sword/dashboard-unfucker#113]
hi, i've been using the unfucker for a while and it's been great, but i noticed today it didn't seem to be working. uninstalled it with the intention of reinstalling, but clicking the link on the main page didn't work. i then tried installing it via URL, also failed to install. not sure  if this is a tampermonkey issues or unfucker, but thought i'd mention it just in case.

EDIT:  it uh.... just randomly started working again? not sure what happened. ignore me lol

**Comment by king-guinevere** [comment]
I'm having this same issue right now. First sign something was up was that I couldn't refresh my dashboard. Had to reload the whole page, and when I did, I got fucking attacked by tumblr's shit twitter clone setup.

hasn't fixed itself like yours yet but ill be regularly refreshing in hopes it does.

**Comment by NicoTheCinderace** [comment]
Bumping this to state that it recently stopped working for me. @enchanted-sword

**Comment by enchanted-sword** [comment]
Should be fixed in v4.3.0.

**Comment by NicoTheCinderace** [comment]
> Should be fixed in v4.3.0.

I've installed v4.3.0, and it's **still** not fixed. :(

**Comment by NicoTheCinderace** [comment]
Fixed via Reinstalling Tampermonkey.

**Comment by king-guinevere** [comment]
I've reinstalled both and it's still not working for me.

**Comment by NicoTheCinderace** [comment]
> I've reinstalled both and it's still not working for me.

That's odd.
