### ISSUE TITLE
Dashboard Unfucker no longer working.

### ISSUE THREAD

**Issue by NicoTheCinderace** [enchanted-sword/dashboard-unfucker#115]
**Describe the bug**
It literally just went back to the new dashboard design for no reason.

**To Reproduce**
Install it and go on Tumblr.

**Screenshots**
None to provide, It explains itself.

**Version (please complete the following information):**
 - Browser and version Firefox 117.0 
 - Version 4.2.1

**Additional context**

**Comment by NicoTheCinderace** [comment]
Going to bump this.

**Comment by enchanted-sword** [comment]
Should be fixed in v4.3.0.

**Comment by NicoTheCinderace** [comment]
> Should be fixed in v4.3.0.

Nope. Not fixed.

**Comment by NicoTheCinderace** [comment]
I think Tumblr must've changed some coding to where the script doesn't work. :/

**Comment by enchanted-sword** [comment]
It works fine for me, and I tested it in multiple browsers with multiple script injectors on multiple computers, so there's likely a more specific issue at play than just "it doesn't work".

**Comment by NicoTheCinderace** [comment]
> It works fine for me, and I tested it in multiple browsers with multiple script injectors on multiple computers, so there's likely a more specific issue at play than just "it doesn't work".

It's weird. I've tried reinstalling it multiple times, it's just... not working for some reason.

Will do some more testing. Something's messing it up.

**Comment by NicoTheCinderace** [comment]
Okay, so it turns out that the issue was resolved after I fully reinstalled Tampermonkey.
