### ISSUE TITLE
Legacy Ediotor not there.

### ISSUE THREAD

**Issue by CKS97** [enchanted-sword/dashboard-unfucker#116]
**Describe the bug**
So I have the "allow legacy editor" checked, but it won't let me use that option when I want to make posts.

**Screenshots**
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/144390392/fcc4ca0e-9092-4527-b3be-74ab61eea015)
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/144390392/01c28752-e25c-49fa-8676-e6fe4029f838)

**Version (please complete the following information):**
 - Firefox, but I checked and this is on other browers such as Opera GX and Google Chrome
 - Dashboard unfucker version v.4.2.1

I just want to know if it's on my end or if it really is a glitch. Please respond at your earliest convenience, thank you!

**Comment by ShotgunsAndSass** [comment]
It's possible the legacy editor no longer exists, and that's why it's not there.

**Comment by enchanted-sword** [comment]
I'm pretty sure the legacy editor is gone for good.
