### ISSUE TITLE
The UI at the top of the screen is now taller than it should be

### ISSUE THREAD

**Issue by VictorLincolnPine** [enchanted-sword/dashboard-unfucker#117]
**Describe the bug**
The UI at the top of the screen is now taller than it should be

**To Reproduce**
I have no idea how to reproduce this. All I know is this happened immediately after updating Firefox browser to version 117.0 (64-bit)

**Screenshots**
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/88147213/6051e5da-c867-4236-9443-1357ec14ee09)

**Version (please complete the following information):**
 - Browser and version [Firefox 117.0 (64-bit)]
 - Version [v4.2.1]

**Additional context**
No other context.

**Comment by enchanted-sword** [comment]
Not sure what causes this and can't replicate it consistently, but if you search something in the searchbar it will fix itself.
