### ISSUE TITLE
dashboard unfucker v4.2.1 not loading in properly on firefox

### ISSUE THREAD

**Issue by dw4nks** [enchanted-sword/dashboard-unfucker#118]
**Describe the bug**
Pretty simple. Whenever I open a new tumblr tab on firefox I have to refresh the page. The extension will not be enabled when I first open a new tab, instead showing tumblr's new default dashboard. 

**To Reproduce**
1. Go to new tab on firefox (version 117.0 64-bit)
2. search or click on the default tumblr URL "https://www.tumblr.com/"
3. Should be tumblr's default dashboard, if not then its something to do with my machine probably
4. refresh page
5. page should not have the extension enabled

**Screenshots**
I attached a small ZIP file of a screen recording to you an idea of just how long the webpage takes to load, but granted its not necessary.

**Version (please complete the following information):**
 - firefox (version 117.0 64-bit)
 - Version v4.2.1
 - Windows 10 version 22H2

**Additional context**
This bug is particularly annoying because it takes a couple of seconds to load the webpage each time, making tumblr desktop functionally load twice as long. Granted the slowness of the webpage may be just a machine issue on my end and not an extension issue; My laptop is pretty slow sometimes and I have a lot of extensions on firefox. 

[Mozilla Firefox 2023-09-08 10-56-18.zip](https://github.com/enchanted-sword/dashboard-unfucker/files/12561809/Mozilla.Firefox.2023-09-08.10-56-18.zip)

**Comment by MizzyMizz** [comment]
Same is happening with Microsoft Edge. It's not loading at all either.

**Comment by NicoTheCinderace** [comment]
Can confirm, this is happening to me.

**Comment by enchanted-sword** [comment]
Should be fixed in v4.3.0.

**Comment by NicoTheCinderace** [comment]
> Should be fixed in v4.3.0.

I've updated, and it's not fixed.

**Comment by NicoTheCinderace** [comment]
And I've tried reinstalling multiple times, too. To no avail.

**Comment by NicoTheCinderace** [comment]
Turns out that I had to reinstall Tampermonkey. The entire thing was buggy for some reason.
