### ISSUE TITLE
Legacy Post Editor unavailable

### ISSUE THREAD

**Issue by TheIrkenLuxray** [enchanted-sword/dashboard-unfucker#119]
**Describe the bug**
Legacy post editor isn't available.

**To Reproduce**
Upon creating a new post or reblogging a post, even one compatible with the legacy post editor, the new editor is used. Additionally, the "enable legacy editor" option is no longer under the advanced config options.

**Screenshots**
![advanced config settings. the option to re-enable the legacy post editor is missing.](https://github.com/enchanted-sword/dashboard-unfucker/assets/25753857/ac1a17bc-0de6-40f5-82e9-a826345cf6ac)

**Version (please complete the following information):**
 - Firefox 117.0
 - Version 4.3.0

**Comment by enchanted-sword** [comment]
The legacy post editor was removed as of 08/09/2023.
