### ISSUE TITLE
Caret icons incorrectly colored

### ISSUE THREAD

**Issue by marcustyphoon** [enchanted-sword/dashboard-unfucker#12]
On a search page:

<img width="277"  src="https://github.com/enchanted-sword/dashboard-unfucker/assets/8336245/b41186e0-af0b-4a15-bbee-18812b5da851">

Looks like the `#managed-icon__caret-thin` rule needs a parent selector so it only applies to the nav menus/blog menu!

**Comment by enchanted-sword** [comment]
Fixed by changing the selector to `${keyToCss("subNav")} use`
