### ISSUE TITLE
Pressing the home button reloads the entire page

### ISSUE THREAD

**Issue by Camwoodstock** [enchanted-sword/dashboard-unfucker#121]
**Describe the bug**
For some reason, clicking on the home button reloads the entire page rather than merely reloading the dashboard embedded inside. The only reason we can find is it tries to redirect from a page called "https://www.tumblr.com/dashboard/following".

**To Reproduce**
Click the home button.

**Screenshots**
...This is extremely unnecessary, but just to be absolutely clear, it's this button: 
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/107432951/3cd7d516-4cb4-4138-9e02-bd019fc0a02b)

**Version (please complete the following information):**
 - Firefox 117.0 (64-bit)
 - v4.3.4a

**Additional context**
We literally don't know if this is a Tumblr issue or a bug with the Unfucker.

**Comment by PhantasmagoricMirage** [comment]
Can confirm, was just writing a bug report on the same thing haha

Additionally, the issue seems to be occuring from v4.3.3 onwards, v4.3.2 is refreshing the dashboard as normal

**Comment by enchanted-sword** [comment]
The redirect only happens if you're on a new account. As for the reload, I'm not sure why, I think it's just the same as before but without the animation frame I was calling. I'll see if I can add a check for active windows so I can use the animation frame trick again.
