### ISSUE TITLE
J/K shortcuts not working as usual

### ISSUE THREAD

**Issue by leaflame** [enchanted-sword/dashboard-unfucker#122]
**Describe the bug**
When using the built-in Tumblr shortcut keys, "J" does not scroll all the way to the next post (leaves the width of an icon of the last post on screen). "K" does not work at all.

**To Reproduce**
1. Be on dashboard
2. Press "J" key
5. Attempt to use "K" to realign
6. See other error (aka nothing happens)

**Screenshots**
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/54085405/7ebe6be4-88c7-46de-851c-e2a87ce149c2)

**Versions**
 - Browser: Firefox 116.0.2
 - Version 4.2.1

**Comment by algometric** [comment]
This is also an issue for me on v4.3.5 on Firefox 117.0 with Tampermonkey.

**Comment by algometric** [comment]
I definitely also see it getting caught on some thin div inside the header:
<img width="558" alt="image" src="https://github.com/enchanted-sword/dashboard-unfucker/assets/22303790/d22824f5-048d-426c-8ff8-ec002c1a1ae3">
but at least it scrolls to the correct position on the new interface. It also works mostly as expected on the latest noflags (4.3.0b) for me (although it doesn't account for the header that gets added back and so hides the tops of posts, but I'd consider that a separate issue entirely).

**Comment by enchanted-sword** [comment]
Initial observation I made trying to problem solve this; it seems to perfectly line up the avatar of the post _above_ with the top edge of the layout. This could have something to do with the horizontal navigation layout having an additional avatar at the top of the timeline. A separate part of this bug I observed is that either every 3 or 4 posts, it skips highlighting a post but still scrolls it into view, and the previous post remains highlighted instead, before jumping directly to the following post with the next keypress.

**Comment by pearlythepirate** [comment]
For some additional troubleshooting fodder:

- Disabling the script in the same install of FFX restores the normal scrolling functionality.
- No option toggle in the script seems to make a difference.
- Zoom setting (i.e. 120%) makes no difference either in my tests.
- Installing Greasemonkey + the script and nothing else in a fresh FFX profile causes this bug to reappear.

I found a potential workaround - I'm not sure if it's outside the scope of this script or not:
From what I can tell each post has an "overall" div. I was able to use FFX's inspector to simply add a -100px offset to the CSS of that div and it appears to fix the issue for the whole page: [Screenshots of original div from clean FFX and modified div from FFX + script](https://imgur.com/a/ASvrzYp)

Perhaps there a place in this script that can modify the "overall" post div to add that 1 CSS change?

**Comment by enchanted-sword** [comment]
Adding an offset to the `impressionLoggingWrapper` causes additional issues, such as it offsetting into the top of the dashboard and being misaligned with the highlighted border.
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/512c6155-5f37-411b-b1d0-543be3b0ab88)

![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/d271298c-e7c0-40d5-bc92-1178e668aa1a)

The latter issue can be solved by instead offsetting the `cell`, but the former issue of it overlapping the bar still remains. However, with some more digging, I did find the solution: offset the entire `main` div by -100px and then offset the bar by 100px to make up for the difference. This keeps all the proper alignments while still fixing the scroll offset.
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/730b3c75-172d-418f-8869-e1bed2c1dc8b)
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/b71af21e-6b19-464c-b12d-ffa3bd5417dc)
