### ISSUE TITLE
Follows you badge duplicates in activity page

### ISSUE THREAD

**Issue by guiltiest-gear** [enchanted-sword/dashboard-unfucker#125]
**Describe the bug**
While in the activity page, the badge that indicates if an account follows you provided by this userscript appears twice next to a username

**To Reproduce**
1. Click on the lightning bolt icon to bring up notifications
2. Click on the See Everything button
3. Observe the activity page and note how the Follows You badge is displayed twice

**Screenshots**
![A screenshot of the tumblr activity page, with the follows you badges duplicated](https://github.com/enchanted-sword/dashboard-unfucker/assets/79071613/c1431930-f1bc-4381-9411-765cca89408a)

**Version (please complete the following information):**
 - Browser and version: Firefox 117.0.1 (64-bit)
 - Version: 4.4.0a

**Additional context**
N/A

**Comment by enchanted-sword** [comment]
I'm guessing that the notifications load weirdly in such a way that it ends up firing the function twice, I'll add a fallback to prevent it from adding multiple labels to a single notification.

**Comment by enchanted-sword** [comment]
Should be fixed in v4.4.1
