### ISSUE TITLE
lack of search icon, posts, likes, following on blog pages

### ISSUE THREAD

**Issue by kawa-z** [enchanted-sword/dashboard-unfucker#127]
**Describe the bug**
When going to any blog's page, the search icon, "Posts", "Likes" and "Following" columns are inaccessible, and are covered up by the most recent/pinned post on that blog

**To Reproduce**
1. Go to https://www.tumblr.com/dashboard
2. Click on the icon of any user on the left side of posts
or
1. Go to https://www.tumblr.com/dashboard
2. Type in the blog's username in the place of "dashboard"

**Screenshots**
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/89338271/b5503239-cc67-4228-855b-23c14ddaefd4)
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/89338271/197ff2bd-4682-4282-8d76-b767f623b186)

**Version (please complete the following information):**
 - Browser : Firefox Developer Edition, version 118.0b9 (64-bit)
 - Version 4.4.2

**Additional context**
Also happens when viewing any post through "https://www.tumblr.com/ [blog name] / [post id]", as shown in the 2nd screenshot

**Comment by enchanted-sword** [comment]
Whoops! Should be fixed now, changed it to just counter the 100px offset with 100px top padding.
