### ISSUE TITLE
Dashboard Unfucker 4.4.2 bug: script hides explore tabs

### ISSUE THREAD

**Issue by AmapolaMystery** [enchanted-sword/dashboard-unfucker#128]
**Describe the bug**
It appears that the Dashboard Unfucker 4.4.2 hides a bar at the top of the explore page, which allows users to switch between tabs and select mosaic mode. This is inconvenient because something that I really enjoy about the script is that it allows me to display three post columns simultaneously, instead of the two that the default dashboard displays since the UI rework.

**To Reproduce**
1. Go to explore page
2. Observe the bar previously mentioned quickly disappear as the script loads in

**Screenshots**
With Dashboard Unfucker off
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/145290681/3273b6be-0924-43af-9517-34eb7ff532cf)
With Dashboard Unfucker on
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/145290681/4886fcc6-c07b-42f9-825b-c358f5427d90)

A potential workaround is to turn off the extension, set my explore preferences in the default dashboard, and then reload the extension, where the content displays as I chose.
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/145290681/d394dc0a-7bcb-48b6-8635-4aae94e56e9d)

**Version (please complete the following information):**
 -FireFox 117.0.1 (64-bit)
 -Dashboard Unfucker version 4.4.2

**Additional context**
-This happens regardless of whether I have the "revert searchbar update" setting on or off.

Additionally: Thank you for the work you do with this script! I would have quit the site already if it wasn't a thing. I love the options to widen the content displayed! I hope you have a lovely day :}

**Comment by enchanted-sword** [comment]
This is already fixed in v4.4.3, but thanks for reporting it!
