### ISSUE TITLE
Messaging has disappeared?

### ISSUE THREAD

**Issue by jenlith** [enchanted-sword/dashboard-unfucker#129]
**Describe the bug**
Messaging:  
- not seeing unread badges on 'open' messages (icons in bottom right corner)  
- not seeing messaging in the top bar at all - icon or unread badge  

**To Reproduce**
1. Go to any tumblr page
2. Click on dashboard-unfucker settings
3. Scroll down to 'revert messaging redesign' - this is either enabled or disabled, doesn't seem to matter

**Screenshots**
See that I have the setting enabled here, and I don't see messaging in the top right. I can't show the lack of unread badge on my open chats, as it wasn't until after I expanded one that I saw the messages I missed (since September 9, but after September 6, since I saw the unread badges then)  
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/87286211/c1252db0-c70e-451c-8220-a3e3a9084ae9)

**Version (please complete the following information):**
 - Browser and version: Firefox 117.0.1 (64-bit)
 - Version v4.4.3

**Additional context**
N/A

**Comment by enchanted-sword** [comment]
Not sure what would cause this, and I can't seem to reproduce it. Can you check and see if the icon is just hidden or not present at all? (Shown here in the inspector)
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/3f0dda60-7486-46c8-9b3a-364f1072cf52)
If it's hidden, it'll be greyed out and have the `style="display: none;"` attribute like the shop and explore icons are for me in the example.

**Comment by jenlith** [comment]
looked into it, turned out i blocked at least the icon with ublock origin. should i keep you posted on the unread badge status/behaviour?

**Comment by enchanted-sword** [comment]
That's probably just a normal Tumblr bug, it voids notifications all the time
