### ISSUE TITLE
Search Icon on users blog not working

### ISSUE THREAD

**Issue by aroacesigma** [enchanted-sword/dashboard-unfucker#133]
**Describe the bug**
Blog search is unable to be clicked on, and buttons on blogs are slightly off? (e.g. i go to follow someone and my mouse has to be in the top half of the button)

**To Reproduce**
1. Click on any user's profile picture to go to their blog page
2. Attempt to click on the search icon (magnifying glass)

**Version **
Firefox 117 on Windows 10

**Additional context**
I can still search by typing in [tumblr blog link]/search/[search term] or /tagged. 
I've switched this on and off, I've also tested it with and without my stylus addons and its definitely this .
Its on all blogs, including my own, my sideblogs, and other users

**Comment by enchanted-sword** [comment]
What script version are you using?

**Comment by aroacesigma** [comment]
4.4.3, sorry for forgetting to include that !!! the issue only started recently i think

**Comment by enchanted-sword** [comment]
The latest version is v4.4.5, updating should fix this.

**Comment by aroacesigma** [comment]
thank you very much !!
