### ISSUE TITLE
Tumblr dashboard unfucker

### ISSUE THREAD

**Issue by DaggrySaga** [enchanted-sword/dashboard-unfucker#136]
My dashboard on Tumblr is in a weird order. Posts I have already seen ends up mixed in with new posts. A friend mentioned it might be due to this script. 

I've tried to update it, and it led me to reinstall. When I tried to reinstall, I got a blank page. 

**Describe the bug**

**To Reproduce**

**Screenshots**

**Version (please complete the following information):**
 - Browser and version [e.g. FF Nightly 118.0a1]
 - Version [e.g. 3.6.2a]
![2023-10-02 (1)](https://github.com/enchanted-sword/dashboard-unfucker/assets/146774023/0ddb4f3a-e268-4721-9ae6-44df0d12f23e)
![2023-10-02 (2)](https://github.com/enchanted-sword/dashboard-unfucker/assets/146774023/f1acde50-d68a-40e8-9966-9b8bb59c0286)

**Additional context**

**Comment by enchanted-sword** [comment]
The dashboard feed not displaying in exact reverse chronological order is a Tumblr thing; not sure if it's a specific feature or just a dashboard settings thing, but I've seen it occasionally before. As for the white screen, that's normal after installing.

**Comment by DaggrySaga** [comment]
Thank you. It did indeed help.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusfri.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Den fre. 6. okt. 2023 kl. 18.14 skrev Frenchi ***@***.***>:
