### ISSUE TITLE
DMs layout

### ISSUE THREAD

**Issue by 8765678cc** [enchanted-sword/dashboard-unfucker#14]
hello! would it be possible to change the DMs layout to the old one? i haven't seen anyone talk about it but i got an update for them (both mobile and desktop) and it looks like twitter too. i hate it. i miss the old dms. thank you

**Comment by marcustyphoon** [comment]
Note that the DM layout experiment is separate from the vertical nav layout experiment, so I think some people will have one but not the other (I have vertical nav and do not have expanded DMs).

**Comment by enchanted-sword** [comment]
I would like to fix it, but I don't have the update so I have no reliable way to make or test a fix for it myself. Until they either make it optional (here's hoping), or roll it out to every user, someone who does have it will have to come up with a fix.

**Comment by 8765678cc** [comment]
i see! thank you nonetheless :)
