### ISSUE TITLE
return the reblogee to the reblog bar.

### ISSUE THREAD

**Issue by draindive** [enchanted-sword/dashboard-unfucker#140]
with the new tumblr updates, it seems that when you reblog posts from someone else, you can't see their name in the 'reblogged from' section. i was wondering if it was possible to return this element to the web dashboard (i think it still exists on mobile tumblr for right now, at least so far as the version i have) because it is a useful feature to have.

**Comment by enchanted-sword** [comment]
I never removed the fix for this after last time they tried to change the headers, chances refreshing your browser should fix it. I encountered it once while testing, refreshed, and haven't seen it since.

**Comment by draindive** [comment]
oh, i see it now, thank you!
