### ISSUE TITLE
Reply from sideblogs feature not working (v5.1.0)

### ISSUE THREAD

**Issue by auvue** [enchanted-sword/dashboard-unfucker#142]
I'm testing out the experimental feature of using sideblogs to reply, but it's not really doing so after just a refresh. 
![Screenshot 2023-10-17 at 00-42-06 Tumblr](https://github.com/enchanted-sword/dashboard-unfucker/assets/148185147/eb55647d-2532-43f3-903b-d217af18bb81)
![Screenshot 2023-10-17 at 00-42-27 Tumblr](https://github.com/enchanted-sword/dashboard-unfucker/assets/148185147/779667c9-f482-4abb-8264-2c9f5da7c0cf)

It'll appear at first after I make the reply as intended, but when I refresh it just registers it as my main account (oldclothes) replying instead of my sideblog (auvue). I'll also receive the notification emails of just my main blog replying to myself. I don't have any other special tumblr extensions like xkit that might cause issue, just plain desktop Firefox.

**Comment by enchanted-sword** [comment]
Apparently Tumblr actually restricts this feature in the backend...but doesn't throw any errors whatsoever and instead just parses it as a normal reply and makes it _seem_ like it's a sideblog reply. Wish I had caught this in the beta testing phase, but better now than in a week lol.
