### ISSUE TITLE
Script fails to load entirely

### ISSUE THREAD

**Issue by Zaneclodon** [enchanted-sword/dashboard-unfucker#144]
**Describe the bug**
The dashboard unfucker script is entirely failing to load, leaving Tumblr in the same state for me as when the script is turned off. I am unable to locate the settings menu. Reinstalling the script has had no effect.

**Screenshots**
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/28819708/26f289ea-4ca9-422c-8ec9-df22bdde2dd7)

**Version (please complete the following information):**
 - Browser and version: Firefox 118.0.2 (64-bit)
 - Script version: 5.2.0

**Additional context**
The script was working last night, but it stopped working tonight.

**Comment by enchanted-sword** [comment]
Can you send any related errors appearing in the browser console? (Not errors related to CORS or ChunkLoadError)

**Comment by Zaneclodon** [comment]
> Can you send any related errors appearing in the browser console? (Not errors related to CORS or ChunkLoadError)

![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/28819708/58c9c48f-7ba8-4c10-a97c-e93d35a1c90a)
[transcript of message below]

Uncaught (in promise) DOMException: The quota has been exceeded.
    updatePreferences https://www.tumblr.com/dashboard?max_post_id=731536411997650944 line 3 > injectedScript:133
    unfuckDashboard https://www.tumblr.com/dashboard?max_post_id=731536411997650944 line 3 > injectedScript:179
    <anonymous> https://www.tumblr.com/dashboard?max_post_id=731536411997650944 line 3 > injectedScript:1069
    b moz-extension://87b29d52-3567-40f8-9c4f-986a425b6099/userscripts/dashboard-unfucker.user.js?id=a672012e-483b-408f-8fd7-97813ab04751:3
    He moz-extension://87b29d52-3567-40f8-9c4f-986a425b6099/userscripts/dashboard-unfucker.user.js?id=a672012e-483b-408f-8fd7-97813ab04751:3
    append moz-extension://87b29d52-3567-40f8-9c4f-986a425b6099/userscripts/dashboard-unfucker.user.js?id=a672012e-483b-408f-8fd7-97813ab04751:3
    findHead moz-extension://87b29d52-3567-40f8-9c4f-986a425b6099/userscripts/dashboard-unfucker.user.js?id=a672012e-483b-408f-8fd7-97813ab04751:1102
    observer moz-extension://87b29d52-3567-40f8-9c4f-986a425b6099/userscripts/dashboard-unfucker.user.js?id=a672012e-483b-408f-8fd7-97813ab04751:1111
dashboard:133

There was also this error, which may be unrelated but I'm including it for completeness:

![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/28819708/b6cc10e9-9c5a-4427-81ac-057a1d690293)
[transcript of message below]

Uncaught (in promise) DOMException: Permission denied to access property "__gpp" on cross-origin object
    registerEventListener https://ib.3lift.com/rev/dce4acbdf274a8d8d0006c89c1d492e048416b86/dist/bundle.js:1
    ht https://ib.3lift.com/rev/dce4acbdf274a8d8d0006c89c1d492e048416b86/dist/bundle.js:1
    ce https://ib.3lift.com/rev/dce4acbdf274a8d8d0006c89c1d492e048416b86/dist/bundle.js:1
    je https://ib.3lift.com/rev/dce4acbdf274a8d8d0006c89c1d492e048416b86/dist/bundle.js:1
    run https://ib.3lift.com/rev/dce4acbdf274a8d8d0006c89c1d492e048416b86/dist/bundle.js:1
    run https://ib.3lift.com/rev/dce4acbdf274a8d8d0006c89c1d492e048416b86/dist/bundle.js:1
    E https://ib.3lift.com/ttj?inv_code=tumblr_d_banner_header:4
    E https://ib.3lift.com/ttj?inv_code=tumblr_d_banner_header:4
    <anonymous> https://ib.3lift.com/rev/dce4acbdf274a8d8d0006c89c1d492e048416b86/dist/bundle.js:1
    <anonymous> https://ib.3lift.com/rev/dce4acbdf274a8d8d0006c89c1d492e048416b86/dist/bundle.js:1
    <anonymous> https://ib.3lift.com/rev/dce4acbdf274a8d8d0006c89c1d492e048416b86/dist/bundle.js:1
bundle.js:1
    registerEventListener https://ib.3lift.com/rev/dce4acbdf274a8d8d0006c89c1d492e048416b86/dist/bundle.js:1
    ht https://ib.3lift.com/rev/dce4acbdf274a8d8d0006c89c1d492e048416b86/dist/bundle.js:1
    ce https://ib.3lift.com/rev/dce4acbdf274a8d8d0006c89c1d492e048416b86/dist/bundle.js:1
    je https://ib.3lift.com/rev/dce4acbdf274a8d8d0006c89c1d492e048416b86/dist/bundle.js:1
    run https://ib.3lift.com/rev/dce4acbdf274a8d8d0006c89c1d492e048416b86/dist/bundle.js:1
    run https://ib.3lift.com/rev/dce4acbdf274a8d8d0006c89c1d492e048416b86/dist/bundle.js:1
    E https://ib.3lift.com/ttj?inv_code=tumblr_d_banner_header:4
    forEach self-hosted:203
    E https://ib.3lift.com/ttj?inv_code=tumblr_d_banner_header:4
    <anonymous> https://ib.3lift.com/rev/dce4acbdf274a8d8d0006c89c1d492e048416b86/dist/bundle.js:1
    <anonymous> https://ib.3lift.com/rev/dce4acbdf274a8d8d0006c89c1d492e048416b86/dist/bundle.js:1
    <anonymous> https://ib.3lift.com/rev/dce4acbdf274a8d8d0006c89c1d492e048416b86/dist/bundle.js:1

**Comment by enchanted-sword** [comment]
Not sure how, but it seems like you've run out of browser storage space. I'm not sure if the quota being exceeded is per site or global, but you might have to clear some storage.

**Comment by Zaneclodon** [comment]
clearing some storage worked, thanks!
