### ISSUE TITLE
Dashboard Unfucker Bug

### ISSUE THREAD

**Issue by penosh** [enchanted-sword/dashboard-unfucker#147]
**Describe the bug**
Clicking post links doesn't show the actual post.

**To Reproduce**
Click on any post link, the post will not be there. Instead the top will say "more from @blogname" 

**Screenshots**

**Version (please complete the following information):**
 - Browser and version [e.g. FF Nightly 118.0a1]
 - FF 118.0.2
 - Version [e.g. 3.6.2a]
 - v5.2.0

**Additional context**

**Comment by enchanted-sword** [comment]
Are there any relevant errors in the console log? I can't reproduce this.

**Comment by penosh** [comment]
Update: It seems to be a problem with vanilla tumblr, not the script itself. Sorry for the false alarm.
