### ISSUE TITLE
content width is a wee bit goofy again

### ISSUE THREAD

**Issue by kitsunegari101** [enchanted-sword/dashboard-unfucker#148]
**Describe the bug**
There's a slight overlap with posts and followed tags; not bad enough to where you can't click on other tags, but enough to be noticeable. Also, the left-hand page margin is nonexistent.

**To Reproduce**
1. click on explore tab

**Version (please complete the following information):**
 - Firefox 119.0 (64-bit)
 - version 5.2.1

**Comment by enchanted-sword** [comment]
The script's content width settings shouldn't affect the explore page. Can you share a screenshot of the issue and your content width/positioning settings?

**Comment by kitsunegari101** [comment]
Sure can!

![unfucker bug](https://github.com/enchanted-sword/dashboard-unfucker/assets/14188767/f624bf7c-eb4d-43fb-81b0-f61cac9814bc)

**Comment by kitsunegari101** [comment]
(didn't mean to close with comment, my bad!)

**Comment by enchanted-sword** [comment]
Really not sure what's happening here, I manually tested different window sizes and couldn't get it to overlap like this. It could possibly be a weird interaction with the version of XKit you're using.
