### ISSUE TITLE
About links having issues.

### ISSUE THREAD

**Issue by pancakeofsin** [enchanted-sword/dashboard-unfucker#149]
**Description of the bug**
The link to the creators blog briefly flashes as if opening a new window, then vanishes within a second. After trying to open creators blog, other links started displaying same behaviour until page was reloaded, now only "My blog" seems to be having issues. Looking at the link preview I am able to navigate to the webpage just fine the blog itself isn't down.

**To Reproduce**
1. Open about section
2. Click "My tumblr!" link.
3. See error.

**Screenshots**
Not applicable.

**Versions:**
 - Mozilla Firefox 119.0
 - dashboard unfucker v5.2.1

**Additional context**
I'm hoping this is just some quirk of the code, because otherwise it does seem a bit. Suspicious. So to say.

**Comment by enchanted-sword** [comment]
Not exactly sure what the issue here is supposed to be. The link target is set to `_blank` so it will normally open in a new tab when possible, if that's what you mean.

**Comment by pancakeofsin** [comment]
Hi, what I meant is that a new tab (or even window if I try to open it in a new one) will flash open and then immediately close

**Comment by pancakeofsin** [comment]
okay, I went to check if the problem still occurs, and after some testing, I think it's client side issues with my uBlock Origin incorrectly recognising some of the links as pop-ups/ads? I'm not super well versed in stuff like this, but I did use ublock to tinker with how the dash looks even before this extension came out, like disabling only the "for you" tab and leaving all others untouched, getting rid of the radar, ect. Ssorry to have bothered you, thank you for making this extension :D
