### ISSUE TITLE
Possible inconsistent following-tab-is-default manipulation

### ISSUE THREAD

**Issue by marcustyphoon** [enchanted-sword/dashboard-unfucker#15]
Take this with a grain of salt, as I could only test this by commenting a bunch of code (my account that has the "for you" tab as the default doesn't have the vertical navigation layout). But:

 - I observed navigating from a non-dash page to the dash not triggering the re-ordering and navigation. `timelineOptionsItemWrapper` probably renders a bit late and thus might need a `waitFor` like the search box.
 - I observed the `navigate()` firing from a non-default dashboard tab, like if you intentionally go to <https://www.tumblr.com/dashboard/hubs> to see posts from your tracked tags. It probably should only override the current location if the user is on the default dashboard. (I used  `if (['/dashboard', '/'].includes(location.pathname)) {  }` in one of my user scripts: basically just a shortened form of your `compare` code using some cool array and window.location builtins!)

**Comment by enchanted-sword** [comment]
Should be fixed in the latest commit
