### ISSUE TITLE
option to stop the scrolling of avatars alongside posts

### ISSUE THREAD

**Issue by bubbykat** [enchanted-sword/dashboard-unfucker#150]
an xkit rewritten update got rid of the option for this because the new layout doesnt have the avatar scrolling feature on the dashboard, but since we obviously dont use the new layout ive once again got scrolling avatars. i feel like its a good accessibility feature for those of us who get sensory overload from it.

**Comment by enchanted-sword** [comment]
Added in v5.2.2!
