### ISSUE TITLE
"revert messaging redesign" appears to have stopped working

### ISSUE THREAD

**Issue by anton-exe** [enchanted-sword/dashboard-unfucker#151]
**Describe the bug**
The messages feature has the redesign, despite the "revert messaging redesign" feature being enabled.

**To Reproduce**
1. Enable "revert messaging redesign"
2. Go into any DM
3. See bug

**Screenshots**
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/43962111/658262f5-c78c-47b4-ac44-b3e75f98ae49)

**Version (please complete the following information):**
 - Firefox 119.0
 - 5.2.1

**Additional context**
This only appears to have began this morning.

**Comment by enchanted-sword** [comment]
Just caught this before updating, it's removed for the time being, but when I have the time I'll look into a pure CSS solution.
