### ISSUE TITLE
Reblog button hangs on screen

### ISSUE THREAD

**Issue by ecojak** [enchanted-sword/dashboard-unfucker#153]
![firefox_2023-11-02_19-01-12](https://github.com/enchanted-sword/dashboard-unfucker/assets/39508599/9682d87b-c152-4d6d-8492-be64b435a3aa)

F5 seems to refresh it, but figured it was worth bringing up.

Firefox version: 119.0 (64-bit), only other extension active is ublock origin.

**Comment by tace94** [comment]
Same thing here, disabled all other extensions but it seemed dashboard unfucker was the cause. Issue started yesterday. Will only go away if I refresh the page. If I go to my dash or anywhere else without refreshing, it stays there until I refresh.
