### ISSUE TITLE
Reverted to new instant messaging

### ISSUE THREAD

**Issue by octonusm9000** [enchanted-sword/dashboard-unfucker#157]
Aww what happened ;( Back to new messaging. I had to uninstall and resintall tamper monkey and when I installed the new dashboard unfucker there's no option to revert back to old messenger

![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/142871971/44dd097f-5e5d-44ee-a897-7dbe42c83cba)

**Comment by enchanted-sword** [comment]
The method I was using to revert messaging stopped working, so now the best I can do is a custom method that uses CSS instead.
