### ISSUE TITLE
New message redesign reverter occasionally a little overzealous about its CSS

### ISSUE THREAD

**Issue by Camwoodstock** [enchanted-sword/dashboard-unfucker#158]
**Describe the bug**
When the message design revert tries to change the header, it also changes the header of the actual Tumblr webpage provided you were previously viewing a blog via the on-Dashboard mini-viewer.

**To Reproduce**
1. Open a blog via the dashboard mini-viewer (for the sake of debugging, do this in a new tab)
2. Go back to the dashboard in the tab you just opened.
3. Open a DM.

**Screenshots**
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/107432951/76b0571c-0ada-47e9-91be-07b9cafa4a3c)

**Version (please complete the following information):**
 - Firefox 119.0
 - 5.3.0

**Additional context**
This seems to only happen if you opened the mini-viewer in a new tab and then revert to the dashboard, but it's possible it can happen without it--we only did that to ensure you can consistently do this.

**Comment by enchanted-sword** [comment]
> 5.3.0

This should already be fixed in the newest version, which is v5.3.2.
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/98f6e378-62b6-40e3-9e0a-ced379498b4b)
