### ISSUE TITLE
"revert messaging redesign" Still Doesn't Work

### ISSUE THREAD

**Issue by Avakining** [enchanted-sword/dashboard-unfucker#160]
**Describe the bug**
The "revert messaging redesign" tweak doesn't work completely

**To Reproduce**
1. Go to dashboard-unfucker settings
2. Scroll down to "revert messaging redesign"
3. Ensure it's enabled
4. It still displays the new design, just slightly smaller

**Screenshots**
Setting on:
<img width="527" alt="A screenshot of the setting enabled, but still not working" src="https://github.com/enchanted-sword/dashboard-unfucker/assets/25210618/6c636443-1855-40a5-a2e7-412602b86cf5">
Setting off:
<img width="527" alt="A screenshot of the setting disabled" src="https://github.com/enchanted-sword/dashboard-unfucker/assets/25210618/d5d84031-7928-47c8-8704-0cf0f6d17eb5">

**Version (please complete the following information):**
 - Firefox Stable 119.0
 - 5.3.2

**Additional context**

**Comment by enchanted-sword** [comment]
That's the extent of what the feature does. The previous messaging layout has since been removed entirely, so this is the closest I could do to revert it.
