### ISSUE TITLE
Activity Feed has zoomed in and cut off avatars

### ISSUE THREAD

**Issue by The-Descolada** [enchanted-sword/dashboard-unfucker#163]
Activity Feed has zoomed in and cut off avatars
<img width="375" alt="tumblr activity feed bug" src="https://github.com/enchanted-sword/dashboard-unfucker/assets/150894527/1d5e073f-8f57-4894-a167-44fd8987e2ec">

 - Firefox
 - 115.3.1esr (64-bit)

**Comment by enchanted-sword** [comment]
Whoops, should be fixed in v5.4.2.
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/f3f58b59-fa13-4eb8-bb3e-49573e82f03a)
