### ISSUE TITLE
dashboard unfucker v5.4.2 not working 

### ISSUE THREAD

**Issue by gaelgar-kallian** [enchanted-sword/dashboard-unfucker#164]
updated firefox to v119.0.1 last night, where the extension was working; then my laptop had some issues between closing it and opening it again when I woke up. however, after having to refresh tumblr due to this, the dashboard-unfucker does not seem to be working. both tampermonkey and the dashboard unfucker are enabled, and disabling/enabling/refreshing doesn't seem to do anything. 

**To Reproduce**
1. go to tumblr.com on firefox v119.0.1
2. if tampermonkey/dashboard unfucker v5.4.2 don't work, you've reproduced it
3. if not, then it's my laptop that's goofed up 

**Screenshots**
![20231117_172529](https://github.com/enchanted-sword/dashboard-unfucker/assets/106069290/43a24b54-ea4f-4bab-8f1e-7421d205390c)

I apologise for the terrible phone photo, it was the only way to show that the extension was enabled 

**Version (please complete the following information):**
 - Browser and version: firefox v119.0.1
 - Version: 5.4.2

**Additional context**
my laptop has a habit it very occasionally likes to do where closing it leaves the screen on, which shrinks the resolution, and it (crashes?) relaunches every single programme. this is easily fixed by closing all the unwanted programmes, changing the resolution in settings, and if microsoft word has crashed dealing with that. I know. it only happens on the rare occasion and my laptop otherwise works fine so I put up with it. since this happened before unavoidably having to reload every tab, it's not impossible this is part of the issue.

**Comment by enchanted-sword** [comment]
Not sure what would cause this, it shouldn't be a compatibility issue with FF 119 since that version worked fine for me back when it was the latest nightly version. Are there any related errors in the browser console?

**Comment by gaelgar-kallian** [comment]
I managed to fix it myself - I switched tampermonkey on and off in my actual extension settings. I don't know if that was what actually did it, because I had tried that earlier, but it worked. that might help with what okaysional is experiencing too? it's worth trying.

**Comment by enchanted-sword** [comment]
@OKaysional the button not working seems to just be a weird coincidence, but when I went to test why the post without tags popup was still appearing for me even with it enabled the popup just stopped showing up completely, so it might just be a case of refreshing Firefox.
