### ISSUE TITLE
"highlight likely bots in the activity feed" doesn't account for "Untitled" in other languages

### ISSUE THREAD

**Issue by anton-exe** [enchanted-sword/dashboard-unfucker#165]
**Describe the bug**

**To Reproduce**
1. Get followed by a bot made with a different language.
2. It's default title is in the set language. An example i've been seeing recently is "Sem título".
3. Due to this, it doesn't get caught by the filter.

**Version (please complete the following information):**
 - Browser: FF 119.0
 - Extension: 5.4.3

**Additional context**
If it helps with making the filter, the polish translation appears to be "Bez tytułu".

**Comment by enchanted-sword** [comment]
Whoops, I had a translation function in the feature but I only just realized that a) it wasn't accounting for that side of things and b) Tumblr's localization data apparently doesn't contain a translation for `Untitled`.
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/afe3d7f3-128a-416b-8869-8f48b867275f)
In that case, I'll have to manually add a list of translations.

**Comment by enchanted-sword** [comment]
I don't have any bots in my notifs to test this on, and I can't test it with my test accounts it doesn't give you notifications when blogs refollow you, but if you still do you can test it out with https://github.com/enchanted-sword/dashboard-unfucker/blob/title-translations/unfucker.user.js

**Comment by enchanted-sword** [comment]
Merged in v5.4.4

**Comment by anton-exe** [comment]
just got a bot in portugese and can confirm it works in case you didn't get one yourself yet
