### ISSUE TITLE
Unable to use script with Firemonkey

### ISSUE THREAD

**Issue by ranidspace** [enchanted-sword/dashboard-unfucker#166]
**Describe the bug**
The script doesn't run at all using Firemonkey. Forcing the script to run gives the message:
```
dashboard unfucker
Failed to insert
redeclaration of const main
```
Opening the script in the built-in editor gives a lot of errors as well.

**To Reproduce**
1. Install Firemonkey and install the script
2. Open Tumblr and view nothing has changed
(Optional steps to further confirm)
3. Click on the addon, and click on the dashboard unfucker script
4. Click "Run"
5. See error described above

**Version:**
 - Firefox 119.0.1
 - Script Version 5.4.3
 - Firemonkey version 2.72
 
**Additional context**
I don't think this is a problem with the script, and rather just a problem with Firemonkey. I see it recommended a lot, but also along with that, the fact that it doesn't support as many scripts compared to the other options. I'm likely going to use Violentmonkey instead, but if this is an easily fixable issue, that'd be great, and if not, there's other options for userscript addons that are less of a hassle.

**Comment by enchanted-sword** [comment]
Weirdly enough, Firemonkey does actually run fine for me, despite the in-browser editor indicating a ton of that syntax errors that proper IDEs and other script injectors don't. I'm not sure why it wouldn't run for you, all I can guess from the error message is that it somehow double-pasted the script, hence the `redeclaration of const main` error (mine pasted three times for some reason at first).

**Comment by ranidspace** [comment]
That might have been it, however I got rid of the script and manually pasted it in myself and put it back in and just got
```
Failed to insert
$ is not a function 
```
new error message! still doesn't work :(

**Comment by enchanted-sword** [comment]
Yeah, it might just be a weird thing with the parser because `$` is definitely a function.
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/47e0d885-80cb-4241-b7bc-260a0fdf5f94)
