### ISSUE TITLE
Remove "Go ad-free today" banner

### ISSUE THREAD

**Issue by Demonskullz** [enchanted-sword/dashboard-unfucker#167]
**Describe the feature**
Remove/hide this recently added banner:
![annoying](https://github.com/enchanted-sword/dashboard-unfucker/assets/102764552/6d58a895-63f8-44ec-8a5b-cbcb0a548c30)
This seems to only appear on your own blog pages (eg. /blog/your-username, /blog/your-username/drafts, etc), but it may appear elsewhere? (I don't know, I killed it on sight.)

**Additional context**
A temporary fix is possible by pasting the following filter into uBlock Origin:
`www.tumblr.com##.HOjIH`
However, this leaves padding artifacts.

**Comment by enchanted-sword** [comment]
Didn't get an email notif for this for some reason but this should now be hidden as of v5.4.4
