### ISSUE TITLE
Space Above Header Menu

### ISSUE THREAD

**Issue by skelebratz** [enchanted-sword/dashboard-unfucker#169]
**Description:**
This is a minor problem, but there appears to be a space above the header menu that was not there before.

**Reproduce:**
I have not found a way to reproduce the issue as it appeared when I opened Tumblr one day.

**Screenshots:**
It does not seem to be a problem of specific data within the HTML or CSS codes of any specific color palette, as it appears in all of them (two examples below)
![Headermenu-trueblue](https://github.com/enchanted-sword/dashboard-unfucker/assets/152046987/0715f5c0-8321-4e55-9e3f-f2132b7f0713)
![Headermenu-gothrave](https://github.com/enchanted-sword/dashboard-unfucker/assets/152046987/449385b6-2022-4451-90f0-83a8b7a98071)

**Versions:**
 - Browser: Firefox v120.0
 - Dashboard Unfucker: v5.4.4

**Comment by enchanted-sword** [comment]
This is a known issue; no idea what the cause is but it should go away if you search something in the searchbar.

**Comment by enchanted-sword** [comment]
Hm, that's strange. I think it's related to the CSS for this element: 
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/091ca973-11a7-4612-aa00-42af79c86f8b)
It doesn't have an implicit height set, so you could try adding a rule to force it to `fit-content`.
