### ISSUE TITLE
Recommended Blogs appear on dashboard even when option is checked

### ISSUE THREAD

**Issue by danareadsbooks** [enchanted-sword/dashboard-unfucker#171]
**Describe the bug**
I have the options to hide recommended blogs checked, but they are appearing on my dashboard now. 

**To Reproduce**
Not sure how to reproduce other than scrolling on dashboard

**Screenshots**
<img width="341" alt="Screenshot 2023-11-30 at 7 20 10 PM" src="https://github.com/enchanted-sword/dashboard-unfucker/assets/152572751/a7691243-93d2-4d6c-8a50-da2d52443632">

<img width="803" alt="Screenshot 2023-11-30 at 7 19 40 PM" src="https://github.com/enchanted-sword/dashboard-unfucker/assets/152572751/68884309-704f-4c0f-9211-10fc137f0009">
<img width="786" alt="Screenshot 2023-11-30 at 7 19 21 PM" src="https://github.com/enchanted-sword/dashboard-unfucker/assets/152572751/e83965c5-bb73-4ff3-9199-f945c517a400">

**Version (please complete the following information):**
 - Browser and version Firefox v. 120.0
 - Version 5.4.4

**Additional context**
I first noticed this today Nov 30. Thank you for helping! Dashboard unfucker is a lifesaver ❤️

**Comment by ArksLanding** [comment]
me too! this started Yesterday? 30th November 2023, but today 1st December 2023, the Recommended Blogs are also back! :O

**Comment by enchanted-sword** [comment]
The timeline recommended blogs being hidden was actually an XKit Rewritten feature (which isn't currently working), but I have added them to the current "hide recommended blogs" feature in v5.4.5!
