### ISSUE TITLE
Not hiding recommended blogs

### ISSUE THREAD

**Issue by emitan** [enchanted-sword/dashboard-unfucker#173]
**Describe the bug**
No longer hides recommended blogs on sidebar since 5.4.5

**Screenshots**

**Version (please complete the following information):**
 - Browser and version Firefox 115.5.0esr
 - Version 5.4.5

**Additional context**
![Screen Shot 2023-12-02 at 11 04 24 PM](https://github.com/enchanted-sword/dashboard-unfucker/assets/8140298/a6c03d5f-d85f-4415-a234-18c70c9c174e)
![Screen Shot 2023-12-02 at 11 04 19 PM](https://github.com/enchanted-sword/dashboard-unfucker/assets/8140298/116860a5-99bf-4e7a-88ce-4d61040f1093)

**Comment by enchanted-sword** [comment]
Are there any related errors in the browser console? It seems to be working fine for me in the latest version, and I haven't changed the code for the sidebar blog recommendations since v5.4.5.

**Comment by emitan** [comment]
I've tried toggling the setting on and off and nothing appears in the browser console.

**Comment by enchanted-sword** [comment]
This and #174 should be fixed in v5.4.7
