### ISSUE TITLE
hide recommended blogs and tags between posts is not working v5.4.6

### ISSUE THREAD

**Issue by NiaMarBla** [enchanted-sword/dashboard-unfucker#174]
With the latest update I clicked the toggle to "hide recommended blogs and tags between posts" but it isn't doing anything. It's definitely checked. I tried uninstalling and reinstalling the script, closing and reopening Firefox, and even restarting my computer but nothing changes. 

Not sure how to reproduce it if it's working on your end, but if there's any data I can provide please let me know and I'll upload it.

Firefox Version 120.0.1
Dashboard Unfucker Version 5.4.6

**Comment by enchanted-sword** [comment]
If you open the browser console and search "[data-carousel-cell]" in the search bar in the Inspector tab, does it return any results like this?
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/a5c81761-1298-4a49-b1d8-4c41091520b6)
