### ISSUE TITLE
Clash with MalwareBytes browser guard, causes huge space to appear at the top of page

### ISSUE THREAD

**Issue by whiteangel123** [enchanted-sword/dashboard-unfucker#175]
**Describe the bug**
When MalwareBytes Browser guard is installed and active, there's a big empty space that suddenly appears at the top of the page. Refreshing multiple times does nothing. I have to deactivate MalwareBytes to get the layout to work again

**To Reproduce**
1. Have MalwareBytes Browser Guard installed 
2. Refresh page
3. See error

**Screenshots**
![TinyTake08-12-2023-12-39-10](https://github.com/enchanted-sword/dashboard-unfucker/assets/36785520/3838b8be-ea52-4b44-bf8d-bf01232b8778)

**Version (please complete the following information):**
 - Browser and version: Chrome 119.0.6045
 - Version: v5.5.0

**Comment by enchanted-sword** [comment]
Not sure exactly why, but MalwareBytes seems to be specifically blocking only this style element, which controls the header wrapper element.
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/084f98bd-b661-4f14-9cff-dd85e4aa474d)
You can see if there's any way to configure MalwareBytes to not block the style element, but if not, you may have to use another extension like Stylus to manually add this style:
```js
#adBanner + div:not(#glass-container) > div:first-child {
  z-index: 100;
  border-bottom: 1px solid rgba(var(--white-on-dark),.13) !important;
  position: -webkit-sticky !important;
  position: sticky !important;
  top: 0 !important;
  min-height: unset !important;
  background-color: RGB(var(--navy));
}
```
