### ISSUE TITLE
Occasionally stops working?

### ISSUE THREAD

**Issue by gaysonlyocean** [enchanted-sword/dashboard-unfucker#176]
I closed firefox and then reopened it only to find the unfucker stopped working, it became working again after a while and then when I closed and reopened it again it had stopped again? I'm really sorry I don't know what's happening or why and decided to reach out. I've tried uninstalling and reinstalling and all that and I can't get it to consistently stay on. I do know Tampermonkey just updated before this started if it helps?

**To Reproduce**
1. Open firefox
2. Close firefox
3. Open firefox again

**Version (please complete the following information):**
 - Firefox 120.0.1 (64-bit)
 - 5.5.0

**Additional context**
I'm sorry to be a bother I don't know any of this coding stuff and I'm worried about it.

**Comment by enchanted-sword** [comment]
It doesn't seem to be an issue with Tampermonkey for me at least, are there any related issues in the browser console?

**Comment by gaysonlyocean** [comment]
Hi! Sorry like I said I don't really know any of this so I apologise if this isn't helpful but this is what it says when I open my browser console:

![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/149696950/5fa69a59-af8c-4f5f-8bb8-7cfef769aa4f)

I did see on tumblr a few other people having the same issue albeit a couple of days ago instead if that help? I'm sorry again I don't really understand coding I just hate the new layout.

**Comment by gaysonlyocean** [comment]
Another update, really sorry for spamming: Now it works if i open and close firefox until I refresh the tumblr tag. I hope that infomation helps?

**Comment by gaysonlyocean** [comment]
I'd like to add on again it's making my laptop's fans really spin up for some reason? Only seems to happen if i turn it off and on again to try to make it work so I know it's caused by it.

**Comment by enchanted-sword** [comment]
No worries. I'm...not exactly sure what console you're looking at right now, but it should be this one (hit F12 in a tumblr tab):
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/d7290de4-314a-4963-9de2-e8fe56046b9c)

**Comment by gaysonlyocean** [comment]
Oh I got it confused with the firefox console sorry!! 

![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/149696950/67956dd7-4a9c-45b5-b887-8759e6fae1e4)
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/149696950/eae2c943-c255-47c3-9f78-689f5e399af3)

Here's what I see there!

**Comment by gaysonlyocean** [comment]
Anything else I can do to help you get to the bottom of this?

**Comment by enchanted-sword** [comment]
The only thing I can think to suggest (although you've probably checked already) is to double-check that the extension and script are active and that the extension has the necessary permissions, other than that I'm not quite sure what to say.
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/0615d981-a124-4e5f-a543-727414a1c47b)

**Comment by gaysonlyocean** [comment]
Yep, it's definitely active. I don't know what happened, it was fine until I closed and reopened firefox earlier.

![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/149696950/a4c44dac-090a-4b1a-b0a5-ea16a488cb92)

**Comment by gaysonlyocean** [comment]
Strange update!! It works if I open tumblr in a private browsing window? I'm really confused.

**Comment by gaysonlyocean** [comment]
Oh! I fixed it by turning off the AVG web browser extension??? That's really strange, I'm really sorry it seems to have been caused by that all along!! But I thank you a lot for your help and assistence here!! You've been really helpful and understanding and I really appreciate it, especially since I don't really understand all of this!! I apologise for taking up so much of your time, I genuinely didn't think it would be AVG of all things causing this!!
