### ISSUE TITLE
"Content Width" slider does the opposite of what is asked

### ISSUE THREAD

**Issue by Golddragon387** [enchanted-sword/dashboard-unfucker#177]
Sliding the "content width" slider to "full width" results in posts being slimmed down so much as to be illegible. Like the first couple of posts in reblog chains back in the old, old tumblr post format.

1. Click on the 'gear' menu
2. Go to 'General Configuration'
3. Scroll down to 'Content Width '
4. Slide the slider all the way to "full width"
5. See screenshot below

**Screenshots**
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/153258781/7a3a944c-2dc4-4b7e-8df1-bef9d7bd8de1)
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/153258781/45ffacc0-e155-4bf7-8403-53156628c7b5)

**Version (please complete the following information):**
 - Firefox V120.0.1
 - Version 5.5.0

**Additional context**
I have no idea how this happened. Issue also persists after scrolling the slider all the way back to 'default.'
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/153258781/f8347d2d-e84e-4af8-8ae5-c15562d56d41)

Reloading with the slider in the 'default' position temporarily resolves the issue, but it recurs when attempting to expand to 'full width again'

**Comment by Golddragon387** [comment]
> I'm also having similar issue with the spacing on my dashboard, but also there's an absolutely incredible amount of space at the top of my dashboard and I cannot for the life of me find what setting is causing this to happen. 

Yeah, I've got that going on as well, but I figured that was something like what's happening in #169 as that goes away when I use the search bar then go back to my dashboard, like described there.

**Comment by enchanted-sword** [comment]
Weird, zero idea why Malwarebytes would cause that without adversely affecting any other parts of the script.
