### ISSUE TITLE
"New XKit" button missing or nonfunctional

### ISSUE THREAD

**Issue by marcustyphoon** [enchanted-sword/dashboard-unfucker#18]
I observe that on the initial page load, the legacy XKit button is sometimes missing from the header, and when one soft navigates anywhere, it appears but doesn't do anything when clicked. (The legacy XKit code is kind of poorly written and tries to add the click handler using `$("#xkit_button")`, but if this userscript runs first and doesn't result in a DOM structure XKit recognizes, the button doesn't get inserted and then `$("#xkit_button")` matches nothing).

This should be easy to solve: as per https://github.com/new-xkit/XKit/blob/master/Extensions/xkit_preferences.js#L88-L103 (which I wrote, as it happens), either there needs to be a `<nav>` element somewhere in the header that this script makes so that the vertical nav layout code gets triggered, or there needs to be a `<header>` element and all of the buttons need a translated `menuContainer` class so the classic layout code gets triggered. My guess is the first one is easier.

**Comment by enchanted-sword** [comment]
Would just something like `$header.append($("<nav>"))` at the end of the script work?

**Comment by marcustyphoon** [comment]
The buttons have to be inside the `<nav>`! So changing the `#__hw` element from a `<div>` to a `<nav>` or doing e.g. `$nav.wrap('<nav>')` should probably work, if they have no other side effects.

**Comment by enchanted-sword** [comment]
Makes sense, I just changed it to a `<nav>` and it seemed to work fine
