### ISSUE TITLE
Content width reduced to 0, unable to change back

### ISSUE THREAD

**Issue by namara-ashina** [enchanted-sword/dashboard-unfucker#183]
Can no longer see posts on my dashboard because everything is condensed into the center. 

**To Reproduce**
1. Click gear icon
2. Switch "content width" to "full width"
3. Everything gets condensed
4. Moving the slider back and forth has no effect

**Screenshots**
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/108107288/9aabc8ec-c120-4d99-8a32-e39555df96ea)

**Version (please complete the following information):**
Firefox 120.0.1 (64-bit)

**Additional context**
Literally just finished clearing my cache/cookies and restarting firefox to the latest version. Now the extension is broken on my dashboard.

**Comment by enchanted-sword** [comment]
This should be fixed in the latest version, as it was previously accidentally including negative values.

**Comment by namara-ashina** [comment]
Didn't realize there was an update button, everything seems to be working now.
