### ISSUE TITLE
No Config Menu visible

### ISSUE THREAD

**Issue by kingofthecrocofiles** [enchanted-sword/dashboard-unfucker#185]
The Script stopped working entirely today. I updated it, but it still has the new layout and I cannot access the config menu to change any settings. I was previously using the NoFlags version and changed to the more recently updated version when it failed to load today. 

I have disabled all other add-ons to view this and nothing makes a difference. 

**To Reproduce**
No idea. It just stopped working.
**Screenshots**
(https://i.gyazo.com/f04194c1651de89ce13e227f7430b105.png)

**Version**
 - Firefox Version 120.0
- Current version of Dashboard Unfucker
- Using latest version of TamperMonkey

**Comment by childofgiants** [comment]
I'm having the same issue, started after TamperMonkey updated to v 5.0.0

**Comment by enchanted-sword** [comment]
Does it work if you change "Modify existing CSP headers" to "Yes" in the Tampermonkey settings?
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/fdb4c911-1117-4492-bb42-fbf3dcca0c7f)

**Comment by childofgiants** [comment]
yup, sorry for being slow on this, but setting csp to yes fixes it.
