### ISSUE TITLE
Links lead to error page

### ISSUE THREAD

**Issue by gnarlystarships** [enchanted-sword/dashboard-unfucker#187]
**Describe the bug**
Any button link I click takes me to some kind of error page. If I refresh, it will show the correct page though.
For example, if I am on my activity page and I click "drafts" I am taken to a white error page with a bunch of code I don't understand. If I refresh the page, it will show me my drafts page though.
This is mainly frustrating when trying to click anything on the dashboard, because the process involves refreshing so the dashboard will be refreshed.

**To Reproduce**
1. Be on any page on tumblr
2. Click any button link; "New Post", someone's username, Followers page, etc.
3. A white and gray error page of some kind appears
4. Refresh page to see the page you were aiming to get to

**Screenshots**
![Tumblr Problem](https://github.com/enchanted-sword/dashboard-unfucker/assets/146762266/30ad18b6-c299-44b3-bc83-0bc269d6dde8)

**Version (please complete the following information):**
 - Browser and version: Firefox 120.0.1 (64-bit)
 - Version: dashboard unfucker v5.5.2

**Additional context**
I hope that I filled this out correctly.

**Comment by enchanted-sword** [comment]
Does this happen without the script active? A similar thing was happening in #180.

**Comment by gnarlystarships** [comment]
It does look similar to #180 but unfortunately when I turn the script off it does solve the problem. 
I deleted and reinstalled the unfucker and it is continuing to have the same problem with those error screens.

The error screens are slightly different for different links I click but they always have the various assets.tumblr.com's with different codes. There is nothing clickable on the error pages though.

**Comment by enchanted-sword** [comment]
Are there any related errors in the console?

**Comment by gnarlystarships** [comment]
How do I find that?

**Comment by enchanted-sword** [comment]
F12 -> Console -> any messages highlighted in red (these ones are unrelated)
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/43b7eb1d-fa25-4076-8032-100f28df06fd)

**Comment by gnarlystarships** [comment]
Apologies for the late reply! I'm not sure what changed, but everything seems to be working now! Thank you for your time.
