### ISSUE TITLE
follows you icon has weird spacing

### ISSUE THREAD

**Issue by chantrykomori** [enchanted-sword/dashboard-unfucker#189]
![Screenshot_1297](https://github.com/enchanted-sword/dashboard-unfucker/assets/16926135/c8e4a4a0-168a-4738-bd6a-65b7736b1a7c)

the styling on this suddenly got weird

**Comment by enchanted-sword** [comment]
Should be fixed in the latest version!
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/691ab413-9cad-42bf-bd58-5194b019f15a)
