### ISSUE TITLE
990px hard crash 2: Electric boogaloo

### ISSUE THREAD

**Issue by enchanted-sword** [enchanted-sword/dashboard-unfucker#19]
Likely because of the new tweaks to the sub-navigation menu, the 990px hard crash is once again an issue. I'm currently not sure how to rearrange the menu items without triggering the crash.

**Comment by marcustyphoon** [comment]
Looks like moving the settings menu breaks it. You could `display: none;` the settings button and menu and make your own to insert into the account menu, possibly?

**Comment by enchanted-sword** [comment]
I just realized I can clone the element with its events and then just change the id and hide the original. I'll test that tomorrow.

**Comment by marcustyphoon** [comment]
Oh, interesting! Curious to see if that works. I can't remember if React's event delegation system tracks what you're clicking on in a way that would make that work or not.

**Comment by enchanted-sword** [comment]
Hm, I'm not sure what but there definitely is something getting messed up with the events that prevents that approach. However, it might be better to just make a new settings menu in the first place and just hide the original because that will let me make it an expandable menu like the blog submenus instead of a popover.

**Comment by enchanted-sword** [comment]
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/ac862963-2bed-4f23-8486-cb312515c307)
Maybe I won't include _all_ the button classes...

**Comment by enchanted-sword** [comment]
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/daa2007a-dd33-406e-9adb-0459bdb66952)
Pretty satisfied with the look of this
