### ISSUE TITLE
Everything looks... messed up?

### ISSUE THREAD

**Issue by cyaperth** [enchanted-sword/dashboard-unfucker#191]
**Describe the bug**
I don't know if it's because of a recent tumblr update that would've messed with dashboard unfucker or something else entirely, but tumblr is near unusable for me now. Textposts either have the lines all garbled or not visible at all, images appear with a blank space with their size beneath them, gifs appear once as normal, once as the first frame of the gif below it, & then the blank space as well. I was able to look at posts' notes until yesterday ; clicking into the notes now does nothing. Like and reblog icons are mostly gone, hyperlink text doesn't have the usual blue colour, all sorts of stuff like that

**To Reproduce**
1. Go to tumblr. That's literally it. The whole thing is bugged for me & i don't know if it'd actually show for anyone else

**Screenshots**
textposts just look like this for me
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/154087943/e74565cd-8702-4cf1-b4f5-c4fc77f03fa4)

i did not censor the username because it's mine haha
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/154087943/6a5ffaa0-9527-471e-afe8-cb35d2408477)

here i visibly have the notes opened but... well not quite
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/154087943/b896570d-2481-4998-ae3e-c4e85ca630d5)

**Version**
 - Firefox version 120
 - Version 5.5.7

**Additional context**
Sorry if this is badly worded, i don't really know how to do this. also sorry if this issue has nothing to do with dashboard unfucker i have no clue what could be causing this it kinda came out of nowhere

**Comment by enchanted-sword** [comment]
To be honest, I have no idea what's going on here. Are there any relevant console errors?

**Comment by cyaperth** [comment]
i'm not too sure how to check that, i'm not very tech-savvy so this is all pretty confusing for me :')

**Comment by cyaperth** [comment]
oh i've got it!! it was cache messing everything up! very sorry for the disturbance, it all works okay now!
