### ISSUE TITLE
Blog avatars no longer displaying

### ISSUE THREAD

**Issue by riderchop** [enchanted-sword/dashboard-unfucker#195]
When Unfucker fully loads, the avatars of the OP posts disappear from the dashboard entirely, no scrolling avatars either.

I'm not sure how to document reproduction of this, but turning DU off does bring them back.

Here's a screenshot and a gif of the icons disappearing
[https://i.imgur.com/UPGujIr.png](url)
[https://i.imgur.com/GZ64M95.gif](url)

Issue found on:
 Chrome 120.0.6099.130 (Official Build) (64-bit)
 Dashboard Unfucker 5.5.8
 - Version [e.g. 3.6.2a]

**Comment by riderchop** [comment]
![GIF 12-20-2023 4-16-25 PM](https://github.com/enchanted-sword/dashboard-unfucker/assets/143557612/a00945e7-fbb2-4654-8754-8e5b5d5bc328)
![chrome_xFqK7L2b7q](https://github.com/enchanted-sword/dashboard-unfucker/assets/143557612/9d5fdb57-2e53-449e-9ce1-ab35b3cd54ad)

realized theres direct media upload lol

**Comment by mount-weary** [comment]
having same issue on firefox 121.0, latest version -- have cleared cache, restarted browser, reinstalled script, etc...
(the pfp will appear briefly as the page is loading, then disappear once fully loaded)
