### ISSUE TITLE
Dashboard avatars are missing

### ISSUE THREAD

**Issue by LemmaEOF** [enchanted-sword/dashboard-unfucker#196]
![Capto_Capture 2023-12-20_02-18-31_PM](https://github.com/enchanted-sword/dashboard-unfucker/assets/6722691/06377b2a-1a33-477a-8e80-feeb82255187)

It looks like Tumblr's reworked some CSS so the unfucker's change to put dashboard avatars back on old layout no longer works. Currently on unfucker v5.5.8 in Safari 16.6

**Comment by mount-weary** [comment]
having same issue on firefox 121.0 -- have cleared cache, restarted browser, reinstalled script, etc...

**Comment by penosh** [comment]
I also have the same issue
