### ISSUE TITLE
can't see avatars

### ISSUE THREAD

**Issue by ritz-writes** [enchanted-sword/dashboard-unfucker#197]
**Describe the bug**
I can't see the avatar's anymore. I just refreshed and suddenly they were gone.

**To Reproduce**
1. Go to dash (that's it)

**Screenshots**
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/154474763/a343b3c9-b041-4033-b24e-701af6a298b9)
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/154474763/e5e9ed64-2d4e-4c1e-8dc6-efbbf044787f)
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/154474763/abe58042-5039-47b3-961b-dd985ad08bf2)

**Version (please complete the following information):**
 - Firefox
 - 121.0

**Additional context**
n/a

**Comment by mount-weary** [comment]
having same issue, same browser

**Comment by crumcake** [comment]
Me three.

**Comment by constantiines** [comment]
glad to know it isn't just me. :(

**Comment by AztralSea** [comment]
Also having this issue, only started for me after I enabled the tag replacer on xkit rewritten

**Comment by penosh** [comment]
I am also having this issue

**Comment by Camwoodstock** [comment]
Same issue here.
