### ISSUE TITLE
Icons Have Disappeared

### ISSUE THREAD

**Issue by Luthien22** [enchanted-sword/dashboard-unfucker#199]
My blog icons have disappeared on Firefox for Desktop. The rest of Dashboard Unfucker is working fine.

![no icons](https://github.com/enchanted-sword/dashboard-unfucker/assets/10780745/0d7bdb8a-9cc6-470c-b3bf-6332f7c235d0)

I'm using Firefox 120.0.1 (64-bit) on Windows.

**Comment by enchanted-sword** [comment]
Already fixed in the latest release

**Comment by Luthien22** [comment]
Wow you're fast. Thanks for all the work you do!
