### ISSUE TITLE
Avatars gone, names nested inside posts again

### ISSUE THREAD

**Issue by Revolos55** [enchanted-sword/dashboard-unfucker#200]
**Describe the bug**
The avatars are no longer to the left of the posts on the main dashboard, and neither are the date/time for queued posts

**Screenshots**
![Screenshot 2023-12-21 at 03-50-46 Queue Tumblr](https://github.com/enchanted-sword/dashboard-unfucker/assets/154505580/969fb30a-993f-45a1-95ee-6e6c68ea1650)
![Screenshot 2023-12-21 at 03-50-14 Tumblr](https://github.com/enchanted-sword/dashboard-unfucker/assets/154505580/d778a16c-7337-4a70-a3db-816fef83cade)

**Version (please complete the following information):**
 - Firefox Version 120.0.1
 - dashboard unfucker v5.5.8

**Additional context**

**Comment by labeedee** [comment]
i'd experienced the same issue, but it was fixed after i'd manually updated to v5.6.0. perhaps you can try that?

**Comment by ErinPhoenix** [comment]
confirmed that manual updating fixed it for me too
