### ISSUE TITLE
Author portraits no longer visible alongside sideblog avatars

### ISSUE THREAD

**Issue by Estecka** [enchanted-sword/dashboard-unfucker#201]
**Describe the bug**

Side blogs have an option to show the portait of a post's author.
On posts from such blogs, this would show a miniature version of the author's main blog avatar, in the bottom right corner of the sideblog's avatar.

As of today, after the fix for the missing avatars everywhere, author portraits are still missing. 

**To Reproduce**
With Dashboard Unfucker, I don't think you ever were able to see author portraits anywhere other than your dashboard. So here's a repro that asusmes you don't follow any blog with that feature enabled, and don't want to follow a rando just for debugging:
1. Create a sideblog. In this blog's setting, check the option "**Show Author portraits**"
3. Post anything.
4. Follow your sideblog, and go find the post on your dashboard.

**Screenshots**
Post as seen in vanilla Tumblr. Author's main blog avatar is visible, laid over the green "reblog" icon. (Asserting that the author information is still publicly available.)
![Vanilla](https://github.com/enchanted-sword/dashboard-unfucker/assets/39855800/e732e347-c125-41be-ba0b-ce502f67cf7c)

Post avatar as seen with Dashboard Unfucker. Only the sideblog avatar is visible.
![Modded](https://github.com/enchanted-sword/dashboard-unfucker/assets/39855800/50202a08-808a-4a67-a6cb-0795c08b1287)

Expected behaviour (screenshot recovered from an older issue)
![Expected](https://github.com/enchanted-sword/dashboard-unfucker/assets/39855800/7f9b0c4f-5d71-4a0f-907e-65da87bc5105)

[Link to the afflicted post](https://www.tumblr.com/e-steack/737317232115335168), just in case. Although any post from that blog would apply.

**Version:**
 - Firefox 121.0
 - Dashboard Unfucker 5.6.0

**Comment by enchanted-sword** [comment]
Fixed in v5.6.1
