### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by Ferinehuntress** [enchanted-sword/dashboard-unfucker#204]
**Describe the bug**
Hello! So I just noticed that the icons that usually show up next to the post are no longer showing up. I also noticed the top icon (mine) sends you straight to the tumblr blog theme rather then the tumblr dashboard theme. Not sure if this is a bug or something that was done on purpose?

**Screenshots**
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/145396687/5024fd64-c9c8-4f8a-9e0a-e07e531c79b1)

**Version (please complete the following information):**
 - Browser used: Firefox
 - Version - dashboard unfucker v5.5.8

**Comment by enchanted-sword** [comment]
Already fixed in later versions

**Comment by Ferinehuntress** [comment]
Thank you <333
