### ISSUE TITLE
icons not showing 

### ISSUE THREAD

**Issue by pnkrabbits** [enchanted-sword/dashboard-unfucker#205]
The icons aren't appearing on the dashboard, while scrolling, even though i have the option for it to show not toggled. Here are some screenshot examples 
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/154560621/ef880397-b4cc-4751-9f9c-be0bb565c649)

![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/154560621/917b6d29-0153-4c63-a15c-14393a161da8)

dashboard unfucker v.5.5.8

**Comment by enchanted-sword** [comment]
That option controls whether or not the icons scroll, not whether or not they appear. You also need to update to the latest version for the latter option.
