### ISSUE TITLE
Disabling avatars scrolling with posts stopped working

### ISSUE THREAD

**Issue by jebra102** [enchanted-sword/dashboard-unfucker#206]
As the title says, despite having the "disable avatars scrolling with posts" option enabled, avatars on the dashboard are back to being sticky. This has started for me today, December 21st. Yesterday I still had zero issues.

![grafik](https://github.com/enchanted-sword/dashboard-unfucker/assets/117840763/6208499d-aab2-4656-8506-bfd3bfebf96f)

 - Browser and version: Firefox 121.0 (64-Bit)
 - dashboard-unfucker version: v5.6.1

I use XKit Rewritten as well but as mentioned above, had zero issues running both simultaneously so far.

**Comment by enchanted-sword** [comment]
It's fixed in the latest commit, but I haven't incremented the version yet since there are a few related bugs I'm waiting to work out.

**Comment by jebra102** [comment]
Ah I see, then I'll just wait for the update. Cheers!

**Comment by enchanted-sword** [comment]
Should be fixed in 5.6.2!
