### ISSUE TITLE
Post size on tag page is smaller

### ISSUE THREAD

**Issue by hellaahydraa** [enchanted-sword/dashboard-unfucker#208]
When viewing a tags page with list view, the post width shrinks in size. Turning off dashboard-unfucker stops the resizing.

Dashboard
![Dashboard](https://github.com/enchanted-sword/dashboard-unfucker/assets/110441702/4ab054dd-8ce6-4385-9201-c7abc96acca2)
Tag Page
![Tag Page](https://github.com/enchanted-sword/dashboard-unfucker/assets/110441702/45930cd5-5744-4f2e-866a-7ca99e3204d4)
Tag Page without Unfucker
![Tag without](https://github.com/enchanted-sword/dashboard-unfucker/assets/110441702/4f89c882-55a0-4bf1-b8cd-363f97a13711)

**Comment by enchanted-sword** [comment]
Fixed in v5.6.3
