### ISSUE TITLE
Avatars not appearing on side of posts on dashboard

### ISSUE THREAD

**Issue by DelphicVoiceAddragh** [enchanted-sword/dashboard-unfucker#209]
Blog avatars are not displaying on the side of posts on the dashboard.
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/108054815/6f6e31ff-a423-47cb-81f5-e6923df368f1)

Browser: Firefox 121.0
dashboard-unfucker version: 5.5.7

**Comment by enchanted-sword** [comment]
Fixed in latest version
