### ISSUE TITLE
Dashboard Types Menu is Hidden

### ISSUE THREAD

**Issue by notdonte** [enchanted-sword/dashboard-unfucker#21]
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/46202918/53dfc7f7-19af-455c-b900-f264d27f33c3)
This bar you use to access the seperate dashboards and... whatever settings menu that manage gives you is entirely inacessible with dashboard unfucker.
Since some are still on default for you for some reason, and others who like having access to followed tags, this bar should probably be moved or reimplemented somehow.

**Comment by enchanted-sword** [comment]
Both this and For You being the default were fixed several updates ago, and dashboard tabs menu now has a toggle in the settings menu
