### ISSUE TITLE
Avatars scrolling with posts again

### ISSUE THREAD

**Issue by spriteatlas** [enchanted-sword/dashboard-unfucker#210]
**Describe the bug**
Despite having 'disable avatars scrolling with posts' enabled, the avatars are scrolling alongside
**To Reproduce**
1. Go to tumblr dashboard
2. Click on the gear next to dashboard unfucker
3. Scroll down to 'disable avatars scrolling with posts' and enable

**Screenshots**
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/139997493/f6414703-db8d-4b13-9b6d-d053f290fb0c)

**Version (please complete the following information):**
 - Browser: Firefox

**Comment by enchanted-sword** [comment]
Version?
