### ISSUE TITLE
Sideblog not viewing on dashboards

### ISSUE THREAD

**Issue by Ferinehuntress** [enchanted-sword/dashboard-unfucker#212]
**Describe the bug**
I will be honest, I don't know if this is something with the dashboard unfucker or if this is something with tumblr. From what I have learned from someone who doesn't use this dashboard unfucker is they see sideblog posts on the dashboard just fine.

However, I have not seen any post, pictures, or any kind of interaction from sideblogs on my dashboard. I am not sure quite how to explain this, just that if you are a side blog (and not a main blog) anything from a sideblog is not featured upon the dashboard when the dashboard unfucker is active.

**Version (please complete the following information):**
 - Browser: Firefox
 - Version: v5.6.1

**Comment by enchanted-sword** [comment]
Not sure exactly what you mean. Sideblog posts show up normally for me, unless you mean specifically author portraits, which only show up if the blog owner has them enabled.
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/88b4f8b1-895f-4914-a955-fd935319c281)
(Also a sideblog, but with no author portrait)
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/7010de6f-1384-4b0e-b41b-66ea21178fd2)

**Comment by Ferinehuntress** [comment]
found out its something I am doing, and I don't knwo what. Just found out its still messed up even with dashboard turend off.

you can close this, sorry. there is somethign wrong on my end either with xkit or something.
