### ISSUE TITLE
Content Width Reverting Randomly

### ISSUE THREAD

**Issue by primarining** [enchanted-sword/dashboard-unfucker#213]
As the title goes, the width of the posts reverts back to default width at random intervals. Does not seem to need a refresh to revert, as sometimes I will only tab out of focus and tab back in to see it reverted. The width scale in the options does not move from where I have it set at, and if I just click the button, it returns back to the proper set width. Other content scaling/movement options seem to be unaffected. 

Other than just browsing tumblr on desktop until it happens, I do not know how to reproduce this.

I am on mozilla firefox 121.0, and dashboard unfucker 5.6.3. I've reinstalled dashboard unfucker and got my settings all set up, but it continues to reoccur.

**Comment by primarining** [comment]
Just found out it also reverts the width when I use CTRL + F.  No other keyboard shortcuts I tried cause it.

**Comment by ChangelingRain** [comment]
yeah I'm getting this too - going from a comfortable 540px wide to 455px wide is real disorienting.

**Comment by enchanted-sword** [comment]
Does it still happen if you manually replace the code with [this version](https://github.com/enchanted-sword/dashboard-unfucker/commit/14c97fc7e712a9d638b1a521663ffb9c141f35bc)? I just realized there was an id conflict between the stylesheet that applies the width settings and the datalist for the input slider so that seems like the most likely cause.

**Comment by primarining** [comment]
Well, I messed up on something in replacing the code, had to reinstall the main script again because it just stopped working, and now it doesn't seem to be doing it, even when I use CTRL + F. I'm

**Comment by primarining** [comment]
Didn't mean to hit that button, as I'm not sure whether or not to consider this closed
