### ISSUE TITLE
Text Automatically Types Backwards

### ISSUE THREAD

**Issue by SugarPining** [enchanted-sword/dashboard-unfucker#214]
**Describe the bug**
Although the Dashboard Unfucker works pretty well for the most part, I've come across this weird bug that keeps popping up. Every so often, when typing, it'll automatically start typing backwards. After doing light troubleshooting, I figured out it only seems to be a problem with the Dashboard Unfucker installed (i.e: I tested using Tumblr on a different browser without the add-on installed, and there were no problems, I refreshed Firefox to where it automatically uninstalled my add-ons, etc.). Although it's a pretty simple fix by just refreshing Firefox and en masse uninstalling my add-ons, I figured it'd be helpful to try and bring this to your attention to see if there's any way to fix this bug.

**To Reproduce**
As far as I know, I don't think it can be reproduced. Maybe it's a problem with my add-ons? But that's a bit of a stretch.

**Screenshots**
![Screenshot 2023-12-25 113222](https://github.com/enchanted-sword/dashboard-unfucker/assets/155020598/9649008e-ba9c-4ae9-b312-0c4c8d26a44e)

**Version**
 - Firefox v121.0
 - Dashboard Unfucker v5.6.3
 - Tapermonkey v5.0.0

**Comment by enchanted-sword** [comment]
I'm not sure if there's any way this could be related to the script...did it start happening again if you reinstalled if after uninstalling everything?

**Comment by SugarPining** [comment]
No, it worked just fine once I uninstalled and reinstalled most of the add-ons. The bug only seems to pop up every once in a while, oddly enough.

**Comment by enchanted-sword** [comment]
But does it only happen with the script installed?

**Comment by SugarPining** [comment]
I did some more testing. When the glitch popped up again, I decided to uninstall Tapermonkey and it still persisted. When I tried running Tumblr on a different browser, and it worked fine.

**Comment by enchanted-sword** [comment]
Definitely not associated with the script then, it's probably tied to some other extension if uninstalling all of them fixed it.
