### ISSUE TITLE
Original Posters not showing up

### ISSUE THREAD

**Issue by mmrobledo** [enchanted-sword/dashboard-unfucker#217]
**Describe the bug**
Icons + usernames from original posters are not showing up on reblogs (both in the dashboard and tumblr.com/blog view) and in reblog chains all user additions only show the text separated by an horizontal line.

**Screenshots**
![Screenshot_1](https://github.com/enchanted-sword/dashboard-unfucker/assets/134395974/2682b0ec-34e1-4c33-a5e4-e88ee386229f)

**Version (please complete the following information):**
 - Browser and version: Firefox Version 121.0.1 (64-bit)
 - Version: 5.6.5

**Additional context**
I tested it with all my extensions disabled and removed + reinstalled this script two times but it doesn't seem to be a problem on my end. Maybe a Tumblr update?

**Comment by enchanted-sword** [comment]
Pretty sure this is caused by the Tumblr Saviour extension, just double-check your settings for it since the developer continually refuses to make it disabled by default.
