### ISSUE TITLE
Posts disappear from dashboard when viewing user's blog

### ISSUE THREAD

**Issue by Zum1UDontNo** [enchanted-sword/dashboard-unfucker#218]
**Describe the bug**
When I click on a user's username to view their blog, and specifically that post on their blog, that post will disappear from the dashboard.

**To Reproduce**
1. Find a post on the dashboard, either in following feed or while searching a tag.
2. Click on the username of a user who made/reblogged that post.
3. Click off that user's blog to return to the dashboard.
4. The post will be removed from the dashboard.

**Screenshots**
Video of the bug in progress.
https://github.com/enchanted-sword/dashboard-unfucker/assets/58796694/bf08cf98-93a6-4452-8a1c-1807fe151ec0

**Version info:**
 - Browser: FireFox 121.0.1 (64-bit)
 - Version: v5.6.6

**Additional context**
No other extensions were enabled, so it's not a conflict with different extensions.
I tested it with all configuration settings enabled, and disabled, and the bug could still be reproduced.

**Comment by enchanted-sword** [comment]
Does it still happen without the script enabled? I couldn't reproduce it as seen in the video.

**Comment by enchanted-sword** [comment]
Not sure, I know there was a bug ages ago where the linked post itself would get voided in blog view but I've never seen it remove posts from the dashboard.

**Comment by TheGeniusIdiotAndStickMerchant** [comment]
I have this bug too, and after having experimented a bit, I experience it after turning on the "revert the post header design and re-add user avatars beside posts" option, but when I turn it off and reload Tumblr, it gets deactivated again.
