### ISSUE TITLE
Inbox Button Disappeared

### ISSUE THREAD

**Issue by Leopardmask** [enchanted-sword/dashboard-unfucker#221]
**Summary**
When dashboard unfucker is active, there is no icon or button to access my tumblr askbox. 

My current settings have the following switches turned on:

- collapse "staff picks" carousel
- revert post header design
- highlight likely bots
- revert activity feed redesign
- revert searchbar update
- disable post without tags nag
- re-add unread post notifications

However, I've experimented with every single switch I have access to and none of them bring back the askbox icon.

**Version (please complete the following information):**
 - Chrome 121 on Windows 10
 - dashboard unfucker v5.6.7

**Additional context**
This used to be tied to the Live icon for some reason - hiding the Live icon also hid the inbox. Now that Live is gone, there's no option that makes the inbox button reappear. It seems like maybe they were connected somehow, but I don't know how or why.

**Comment by enchanted-sword** [comment]
See #219
