### ISSUE TITLE
Wrong exact vote count on in reblog polls.

### ISSUE THREAD

**Issue by TheGeniusIdiotAndStickMerchant** [enchanted-sword/dashboard-unfucker#222]
**Describe the bug**
When there's a reblog chain with polls, and you have "display exact vote counts on poll answers" enabled, the exact vote count only works for the top poll in the chain. The rest use that reblog count.

**To Reproduce**
1. Ensure "display exact vote counts on poll answers" is enabled.
2. Go to [this post](https://www.tumblr.com/thegeniusidiotnstickmerchant3728/741284415643222016/could-you-already-do-this-before-tumblr-added-this)
3. Scroll down.

**Screenshots**
![afbeelding](https://github.com/enchanted-sword/dashboard-unfucker/assets/136821116/3effd36f-77bf-4aa6-b4e6-ebeb8496573a)

**Version (please complete the following information):**
 - 122.0
 - v5.6.7

**Comment by enchanted-sword** [comment]
I hadn't encountered any polls in reblogs since it was a beta feature for a long time, I think I fixed this in my extension port so I'll just reuse those methods.

**Comment by enchanted-sword** [comment]
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/69af2954-abf7-4fed-ab45-2f6d04f886db)
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/eb5b9b88-e3fc-492f-b275-b7bae4c9b6d7)
Looks fine now
