### ISSUE TITLE
Posts posted or reblogged by users with badges don't load on first load when the dashboard unfucker is active

### ISSUE THREAD

**Issue by ChangelingRain** [enchanted-sword/dashboard-unfucker#225]
Reloading, or turning off the unfucker, 'reveals' these posts.

**Comment by lula111** [comment]
Posts from users with badges not showing up at all, which causes the dashboard to glitch and jump around sporadically. Reloading the page can temporarily stop the glitch, but when you scroll to the point that a user with a badge's post is missing, it glitches again. Trying to open the user's page in popover mode causes all posts to glitch and not load.

**Comment by LadyEclipse3** [comment]
I am also experiencing this problem, but as this project is no longer being updated and maintained, it is likely not going to be fixed. We might finally have to accept the twitterification folks.

**Comment by Pacicidal** [comment]
You may have better luck with the Old Tumblr Dashboard userstyle project by Pixiel. It requires the Stylus extension to be installed, but at the time of writing this, it isn't experiencing the same issue, and for the time being, is still being maintained.

It can be found [here](https://www.tumblr.com/pixiel/723402150351437824/anyway-i-created-a-stylish-stylus-that) on Pixiel's Tumblr.

If the markdown link doesn't cooperate, the full one is:
https://www.tumblr.com/pixiel/723402150351437824/anyway-i-created-a-stylish-stylus-that

**Comment by LadyEclipse3** [comment]
Worked like a charm, thanks!
