### ISSUE TITLE
Room for improvements

### ISSUE THREAD

**Issue by m3k1e** [enchanted-sword/dashboard-unfucker#23]
Hello there, I've been using this script for a while but I think there should be a room for improvement for the following reasons.
![chrome_J40Thw1KQp](https://github.com/enchanted-sword/dashboard-unfucker/assets/41316133/c7cf5177-e355-4769-9b75-07118653f7d2)

1. The text on recommended blogs is black and isn't visible to the background.
2. At least make the UI on the right scrollable as well.
3. Maybe I'd suggest changing the vulgar title to either "Better Tumblr" or "Dashboard Restore" because imagine if I wanted to screencap my tumblr page and post it in front of a Discord server that don't allow swear. Just unfucking fuck fuck fuck.
4. My chrome version is 115 and Tumblr Unf**ker version is 2.0

**Comment by enchanted-sword** [comment]
I fixed the selector issue but as for the latter, no offense but I really don't care. Fork it if you want to.
