### ISSUE TITLE
Using the 'J' key to scroll through posts doesn't properly align the top of the post with the header

### ISSUE THREAD

**Issue by its-gareef** [enchanted-sword/dashboard-unfucker#24]
This is very minor and not a huge issue, but I scroll by hotkeys regularly and having the top of a post cut off is a mild annoyance.

**Comment by enchanted-sword** [comment]
This unfortunately seems to be handled by a script on Tumblr's side. I even tried changing the class of the container to the class used by the old layout, but the script seems to scroll the top of the posts to a set width below the top of the screen. I was able to alleviate it a bit in the latest commit by getting rid of a negative top margin on the `tabsHeader` element, but it still overlaps a bit.
