### ISSUE TITLE
Visibility of Dashboard-unfucker settings

### ISSUE THREAD

**Issue by RainbowRider64** [enchanted-sword/dashboard-unfucker#25]
If you use certain dark tumblr themes such as goth rave dashboard-unfucker settings are not very visible.
![dfhggdfhdhj](https://github.com/enchanted-sword/dashboard-unfucker/assets/49082735/a8409a13-8949-4691-9448-c4f2bd1b1529)

**Comment by enchanted-sword** [comment]
Fixed in the latest commit
