### ISSUE TITLE
Individual blog menu dropdown disappeared

### ISSUE THREAD

**Issue by StylusSigil** [enchanted-sword/dashboard-unfucker#28]
Previously didn't have this problem, but the dropdown function seems to have disappeared from the blog menu recently (it used to appear next to the organization icon). Without it there's no way I can find to access blog settings/drafts/followers without disabling the script.

![Screenshot (2702)](https://github.com/enchanted-sword/dashboard-unfucker/assets/90228796/99e1f2b5-decc-4d8e-894b-8406721516dd)

**Comment by enchanted-sword** [comment]
that's an update on tumblr's side, not mine, and, you're also using an outdated version of the script
