### ISSUE TITLE
when resizing window, site throws an error and forces reload

### ISSUE THREAD

**Issue by autumn876** [enchanted-sword/dashboard-unfucker#3]
title, it turns out the node thing from my earlier issue was from me leaving and re-entering fullscreen on firefox. for convience the error is "Unexpected Application Error!
Node.removeChild: The node to be removed is not a child of this node". I can work around for the time being but it is kinda annoying to have to do

**Comment by enchanted-sword** [comment]
this seems to be caused by tumblr attempting to modify the page layout when crossing the breakpoint for the compact layout. i'm not sure it's possible to modify the document to the extent required to fix it while not changing the dom node hierarchy.
