### ISSUE TITLE
missing reblog chain

### ISSUE THREAD

**Issue by hhoffman14** [enchanted-sword/dashboard-unfucker#34]
The first three posts on my dash have icons and reblog chain information, and all posts after that are missing those. I saw the previous profile picture issue, which I also have, and appears to coincide with this bug in that posts with profile pictures have reblog chains and posts without pfps do not.

first post: 
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/29207016/aea3f9a2-efc5-4c22-ac03-9efd7c55f640)
later post:
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/29207016/cbdcab4f-4b6d-4d6c-bbe3-000c5ba88de0)

If I click the header of the post and go to the blog, the reblog chain will show up.

this happens in both versions of the script (version A 3.2.4 and version B 3.2.2)

**Comment by enchanted-sword** [comment]
This is a server-side Tumblr issue, and not related to the script.
