### ISSUE TITLE
Issues when searching a tag on v.3.2.2b

### ISSUE THREAD

**Issue by JustAnotherHaiku** [enchanted-sword/dashboard-unfucker#35]
In this image, the buttons are missing:
![tumblrdashbug](https://github.com/enchanted-sword/dashboard-unfucker/assets/142448502/ee449c97-48e2-41bd-9a57-d5b7fed15be0)
While in this image, the content isn't centered, like I remember it being. The version I downloaded was 3.2.1 at first, so I went to update it because I noticed the option, but it provided similar results. This seems to be what happens most of the time. (I'd prefer it if there was more content presented per row too, but I imagine that's harder to do.)
![tumblrdashbug2](https://github.com/enchanted-sword/dashboard-unfucker/assets/142448502/5451189b-50e7-4a95-a598-380515922dd6)
I have "hide recommended blogs" unchecked, but otherwise I haven't messed with it at all.

**Comment by enchanted-sword** [comment]
It's a bug related to the content positioning slider, I'll include the fix for it in the next update to the version B script.
