### ISSUE TITLE
Issue with legacy editor reversion

### ISSUE THREAD

**Issue by TheIrkenLuxray** [enchanted-sword/dashboard-unfucker#37]
On version v3.3.0a, the legacy editor is brought back on reblogged posts, but I can't get it to work when making new posts. I've switched the box on and off and reloaded multiple times. I am using Firefox.

**Comment by enchanted-sword** [comment]
I've been working on fixing this, but it's just a matter of going through and testing a bunch of different setting combinations to find out which one it is that controls the editor for new posts specifically.
