### ISSUE TITLE
Tag search content positioning issue

### ISSUE THREAD

**Issue by AshSabine** [enchanted-sword/dashboard-unfucker#38]
While doing a tag search everything is all the way off to the side.
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/129895468/6645e6a1-674e-4906-b541-c7cb3c099b39)

**Comment by enchanted-sword** [comment]
I fixed this last commit but forgot to update the version
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/33d3e07c-8716-42b5-b77e-14254eb52869)
