### ISSUE TITLE
"ReferenceError: tumblr is not defined" in console on FF with Greasemonkey with the -noflags version of the script

### ISSUE THREAD

**Issue by kassienull** [enchanted-sword/dashboard-unfucker#41]
I'm running this on Firefox under Greasemonkey. When I try and use the script, I get this error in the dev console:
```
ReferenceError: tumblr is not defined
```

Clicking where Firefox says the error is coming from (just labelled as "sandbox eval context"), I see it's coming from [here](https://github.com/enchanted-sword/dashboard-unfucker/blob/main/unfucker-noflags.user.js#L830). Any idea how to fix this?

**Comment by em-ri** [comment]
Was having the same issue - switched from Greasemonkey to Tampermonkey and it's working fine now.

**Comment by kassienull** [comment]
Is there a way to make it work with Greasemonkey? (Or, alternatively, can GM+TM run side-by-side)? I have a few dozen scripts in Greasemonkey already that I wrote that I'd prefer to not have to re-test in Tampermonkey.

**Comment by enchanted-sword** [comment]
I would imagine you could use both at once.

**Comment by marcustyphoon** [comment]
Greasemonkey probably doesn't inject scripts into page context. Violentmonkey and Tampermonkey have options about which context you want to run a script in. You might be able to get around this using `unsafeWindow`, especially with the noflags version, but I don't know if the flags version would work that way (there are ways around this, like injecting the whole script as a script tag body).

**Comment by enchanted-sword** [comment]
Greasemonkey compatibility should be fixed in v3.3.1b. Oddly enough, the same fix doesn't seem to work for Tampermonkey Beta.

**Comment by marcustyphoon** [comment]
Possibly because `// @grant none` disables the sandbox entirely in Violentmonkey and Tampermonkey; see https://violentmonkey.github.io/api/metadata-block/#grant and https://www.tampermonkey.net/documentation.php?locale=en#meta:grant. Not familiar with the exact differences between those and Greasemonkey and how to fulfill every requirement at once since I've only used those two.

**Comment by enchanted-sword** [comment]
I did catch that earlier, I changed it to `// @grant unsafeWindow`
