### ISSUE TITLE
polls hidden?

### ISSUE THREAD

**Issue by krc** [enchanted-sword/dashboard-unfucker#42]
Screenshots of poll and title not being visible with dashboard-unfucker turned on, and then visible with it turned off:

![Screenshot 2023-08-18 at 00-56-18 Tumblr](https://github.com/enchanted-sword/dashboard-unfucker/assets/211671/a9e839c5-196a-44bb-ac00-e0980098349b)
![Screenshot 2023-08-18 at 00-56-29 like honey bees to do the same](https://github.com/enchanted-sword/dashboard-unfucker/assets/211671/bf4d8b6b-e53e-4262-b45e-55d8ca0b9936)
![Screenshot 2023-08-18 at 00-57-11 Tumblr](https://github.com/enchanted-sword/dashboard-unfucker/assets/211671/a068aa8d-5d1e-48e1-a85d-183db462093d)

Nothing else changed, just deactivated and reloaded. on reactivating and reloading it was gone again. 
FF developer edition 117b9 on Win10, with XKit Rewritten. 

OP url of poll https://www.tumblr.com/honeylemony/725412032931889152/how-long-does-it-take-you-to-naturally-fall-asleep

**Comment by enchanted-sword** [comment]
You could try disabling the "enable adding polls to reblogs" option. Other than that, I don't know what would potentially cause that on 3.4.0a.

**Comment by krc** [comment]
Oh! I had turned off "enable adding polls to reblogs" at the get-go... just now turned it *on* and the polls reappeared!
