### ISSUE TITLE
help im a noob

### ISSUE THREAD

**Issue by ghost-thoast** [enchanted-sword/dashboard-unfucker#43]
The resource at “https://assets.tumblr.com/pop/src/assets/fonts/favorit/favorit-medium-fbc7316f.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. dragongirlsnout
The resource at “https://assets.tumblr.com/pop/src/assets/fonts/favorit/favorit-85-cf2f6136.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. dragongirlsnout
Content-Security-Policy: Ignoring “'unsafe-inline'” within script-src: nonce-source or hash-source specified dragongirlsnout
Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). content.js:64:422
Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). content.js:65:165
Loading failed for the <script> with source “https://s0.wp.com/wp-content/js/bilmur.min.js?m=202333&f=3”. dragongirlsnout:344:3
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://assets.tumblr.com/pop/js/modern/sentry-579c304a.js. (Reason: CORS request did not succeed). Status code: (null).
<script> source URI is not allowed in this document: “https://assets.tumblr.com/pop/js/modern/sentry-579c304a.js”. dragongirlsnout:1:1
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://assets.tumblr.com/pop/js/modern/sentry-579c304a.js?1692367142473. (Reason: CORS request did not succeed). Status code: (null).
<script> source URI is not allowed in this document: “https://assets.tumblr.com/pop/js/modern/sentry-579c304a.js?1692367142473”. dragongirlsnout:1:1
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://assets.tumblr.com/pop/js/modern/sentry-579c304a.js?1692367143592. (Reason: CORS request did not succeed). Status code: (null).
<script> source URI is not allowed in this document: “https://assets.tumblr.com/pop/js/modern/sentry-579c304a.js?1692367143592”. dragongirlsnout:1:1
ChunkLoadError: Loading chunk 2897 failed after 2 retries.
(js/modern/sentry-579c304a.js)
    j https://assets.tumblr.com/pop/js/modern/runtime-c4dd1a23.js:1
    e https://assets.tumblr.com/pop/js/modern/runtime-c4dd1a23.js:1
    e https://assets.tumblr.com/pop/js/modern/runtime-c4dd1a23.js:1
    e https://assets.tumblr.com/pop/js/modern/runtime-c4dd1a23.js:1
    e https://assets.tumblr.com/pop/js/modern/runtime-c4dd1a23.js:1
    setTimeout handler*r.e/</< https://assets.tumblr.com/pop/js/modern/runtime-c4dd1a23.js:1
    e https://assets.tumblr.com/pop/js/modern/runtime-c4dd1a23.js:1
    promise callback*r.e https://assets.tumblr.com/pop/js/modern/runtime-c4dd1a23.js:1
    e https://assets.tumblr.com/pop/js/modern/runtime-c4dd1a23.js:1
    setTimeout handler*r.e/</< https://assets.tumblr.com/pop/js/modern/runtime-c4dd1a23.js:1
    e https://assets.tumblr.com/pop/js/modern/runtime-c4dd1a23.js:1
    promise callback*r.e https://assets.tumblr.com/pop/js/modern/runtime-c4dd1a23.js:1
    u https://assets.tumblr.com/pop/js/modern/main-30b6100d.js:136
    21669 https://assets.tumblr.com/pop/js/modern/main-30b6100d.js:90
    r https://assets.tumblr.com/pop/js/modern/runtime-c4dd1a23.js:1
    t https://assets.tumblr.com/pop/js/modern/main-30b6100d.js:136
    <anonymous> https://assets.tumblr.com/pop/js/modern/main-30b6100d.js:136
    O https://assets.tumblr.com/pop/js/modern/runtime-c4dd1a23.js:1
    <anonymous> https://assets.tumblr.com/pop/js/modern/main-30b6100d.js:136
    a https://assets.tumblr.com/pop/js/modern/runtime-c4dd1a23.js:1
    <anonymous> https://assets.tumblr.com/pop/js/modern/main-30b6100d.js:1
main-30b6100d.js:136:3171
The resource at “https://assets.tumblr.com/pop/src/assets/fonts/favorit/favorit-medium-fbc7316f.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. dragongirlsnout
The resource at “https://assets.tumblr.com/pop/src/assets/fonts/favorit/favorit-85-cf2f6136.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. dragongirlsnout
ReferenceError: tumblr is not defined page.js line 67 > eval:470:24

**Comment by enchanted-sword** [comment]
The only one of those that seems to actually be caused by the script is the last one. What script injector are you using?

**Comment by ghost-thoast** [comment]
Tampermonkey BETA. I know nothing about coding. how do i fix the rest? Do they need to be fixed?

**Comment by enchanted-sword** [comment]
The rest are fine. You could try using the non-beta version of Tampermonkey and see if that fixes it.

**Comment by ghost-thoast** [comment]
THANK YOU. At last my dash is unfucked!
