### ISSUE TITLE
Doesn't seem to work on firefox with violentmonkey?

### ISSUE THREAD

**Issue by go4ino** [enchanted-sword/dashboard-unfucker#44]
Firefox 64 bit version 116.0.3
ViolentMonkey 2.15.0
XKit rewritten 0.21.15

Tried both scripts and dashboard layout stayed the same after restarting Firefox

![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/2292520/74e1e443-5cde-4ab3-b493-127c274ddf60)

**Comment by enchanted-sword** [comment]
Can you check the browser console for related error or warning messages? It should be compatible with Violentmonkey, so the bug could be elsewhere

**Comment by go4ino** [comment]
Yup got plenty of console window errors when i launch firefox

here are the console errors when i search for fuck / unfuck

ig the error is it has trouble actually injecting the script to tumblr?

```
cannot inject content script /js/initialize_contentscripts.js into url https://github.com/enchanted-sword/dashboard-unfucker/issues/new on tab 26 and frame 0 [utils.js:188:15](moz-extension://04a3d052-22c1-4e95-83b4-4fa28a485bd8/js/utils.js)
cannot inject content script /js/initialize_contentscripts.js into url https://github.com/enchanted-sword/dashboard-unfucker/blob/main/unfucker.user.js on tab 27 and frame 0 [utils.js:188:15](moz-extension://04a3d052-22c1-4e95-83b4-4fa28a485bd8/js/utils.js)
Navigation error
      tabId: 27
      url: https://github.com/enchanted-sword/dashboard-unfucker/blob/main/unfucker.user.js
      error: Error code 2147500036 [utils.js:188:15](moz-extension://04a3d052-22c1-4e95-83b4-4fa28a485bd8/js/utils.js)
Navigation error
      tabId: 26
      url: https://github.com/enchanted-sword/dashboard-unfucker/issues
      error: Error code 2152398850 [utils.js:188:15](moz-extension://04a3d052-22c1-4e95-83b4-4fa28a485bd8/js/utils.js)
cannot inject content script /js/initialize_contentscripts.js into url https://github.com/enchanted-sword/dashboard-unfucker/issues/44 on tab 26 and frame 0 [utils.js:188:15](moz-extension://04a3d052-22c1-4e95-83b4-4fa28a485bd8/js/utils.js)
```

**Comment by enchanted-sword** [comment]
Those logs are from this github page, not Tumblr

**Comment by Rayquaza01** [comment]
I'm having the same issue with Violentmonkey on Firefox. The only error I see related to this script is the same one mentioned in #41

**Comment by krc** [comment]
Oh I saw that violentmonkey was removed from the readme, so I thought it was officially dropped. 3.4.0 also didn't work for me at all with violentmonkey... didn't investigate since I thought it was dropped, but I could if more is needed

**Comment by enchanted-sword** [comment]
I didn't mean to remove it, I think I must have forgotten to sync my local copy on the computer I last pushed a commit from.

**Comment by go4ino** [comment]
ok heres the tumblr specific error i think

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://assets.tumblr.com/pop/js/modern/sentry-5fa7928f.js. (Reason: CORS request did not succeed). Status code: (null).
```

**Comment by enchanted-sword** [comment]
That's an error thrown by the site itself

**Comment by go4ino** [comment]
oh rip my bad

is there anything i should look out for to single out unfucker issues?

**Comment by enchanted-sword** [comment]
Any errors the script itself throws will look something like this
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/3a049fe4-385f-4f2c-ae07-cf77fb989043)

**Comment by rowanreader** [comment]
I'm having a similar issue I think? I used Tampermonkey to save the script and it is showing up on my Tampermonkey dash, but it doesn't seem to get applied to my tumblr. 
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/33907861/aa68aab1-05d4-409c-8fa1-e859c4c3b694)
I looked at my browser console log and this is what it showed - I tried searching through the error tab for 'uncaught', 'reference',  'tamper' and 'unfuck' but none of those had anything.

**Comment by enchanted-sword** [comment]
I think that's a different console, try just hitting F12 on a tumblr page and going to the "Console" tab
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/b651f5f9-478d-4ebe-8a25-50a4a478e5db)

**Comment by go4ino** [comment]
Got nothing for errors when i launch the tumblr website

Maybe I installed it incorrectly? 


![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/2292520/47bd09ba-6d29-44e8-8ae3-44066b3cea10)

![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/2292520/b5049dec-a767-4260-8fb5-5a58f084d6b0)


![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/2292520/3164c610-37a0-4baa-ba0d-f412277149bd)

**Comment by rowanreader** [comment]
> I think that's a different console, try just hitting F12 on a tumblr page and going to the "Console" tab ![image](https://user-images.githubusercontent.com/81981111/261866604-b651f5f9-478d-4ebe-8a25-50a4a478e5db.png)
Ah yep that was a different console. Errors are:

![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/33907861/a1969106-4f86-41d9-81d4-74ed342ce22f)

**Comment by go4ino** [comment]
Yup that screen dont got any results when i search for `unfucker`

Dont see any errors. Is there a tab to see all processes and not just errors/ warnings?

![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/2292520/6a2cf60e-7140-487a-9689-066d26df39cf)


![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/2292520/50032192-c1b6-4b11-896c-d6bbd82f8d2c)

**Comment by rowanreader** [comment]
Update: turns out my tampermonkey script wasn't enabled - enabled it and it now works!

**Comment by enchanted-sword** [comment]
Closing this because it's turned into a jumble of different issues, and because the original bug was probably a CSP issue and as of v3.5.0a and v3.3.2b both scripts now uses `unsafeWindow` and should inject fine regardless.

**Comment by go4ino** [comment]
Update: For some reason in firefox opening `devtools` with `F12`, going to settings and checking the `Enable browser chrome and add-on debugging` option got the script to start running
