### ISSUE TITLE
Algorithmic Content Appearing

### ISSUE THREAD

**Issue by Steel-Aurora** [enchanted-sword/dashboard-unfucker#45]
Using this script is causing Tumblr Live and Recommended Blogs to appear for me, even though I have those things turned off in my account settings and in my XKit Extension that I also use. Here's a screenshot I took of Tumblr Live popping up despite these settings.
![Screen Shot 2023-08-18 at 1 28 28 PM](https://github.com/enchanted-sword/dashboard-unfucker/assets/142629283/fde4d598-10d0-45a0-bb39-31d83ebad3a1)

**Comment by enchanted-sword** [comment]
Do you have live and recommended blogs disabled in the script preferences? If not, it could be overriding XKit.

**Comment by Steel-Aurora** [comment]
I do, but they still seem to be popping up.
![Screen Shot 2023-08-18 at 1 45 10 PM](https://github.com/enchanted-sword/dashboard-unfucker/assets/142629283/07691747-b720-426f-a95a-aff6456f706d)

**Comment by enchanted-sword** [comment]
Weird. I can't replicate this, so all I can suggest is to try toggling them on and off again, or trying the other version of the script if you haven't already tried it.

**Comment by Steel-Aurora** [comment]
Hey, I tried Type A and it seems to be working better! Haven't seen any algorithmic stuff after installing that. Thank you for the help!

**Comment by enchanted-sword** [comment]
No problem!
