### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by HyllaAldan** [enchanted-sword/dashboard-unfucker#46]
Hello! I just installed Version B of your dashboard unfucker, and it works great aside from one small thing. Every time I refresh the page, or close Tumblr and open it in a new tab, all of my chosen settings have been reset (despite all of the boxes I checked off remaining as such) and all of the stuff I chose to hide, like Tumblr live, the shop, etc., just show up all over again. Thank you so much, and have a great rest of your day!
![Screenshot 2023-08-18 233943](https://github.com/enchanted-sword/dashboard-unfucker/assets/142652852/ad81430f-e427-4630-acd5-27e8b7698f07)
![Screenshot 2023-08-18 234032](https://github.com/enchanted-sword/dashboard-unfucker/assets/142652852/81d7f1e8-dcc1-486e-bbcd-ed52ef7d7da2)

**Comment by enchanted-sword** [comment]
This might be a compatibility issue with New XKit. If the type A doesn't cause other issues for you, switching to it should at least fix tumblr live appearing.
