### ISSUE TITLE
messages don't open unless viewing blog on dashboard

### ISSUE THREAD

**Issue by frenchifries** [enchanted-sword/dashboard-unfucker#47]
i noticed clicking on a message in my messages list won't actually cause the message to open (whether i have the message redesign enabled or disabled, and whether i'm using the current or reverted dashboard layout). it's only when i click on someone's icon/url to open their blog in dashboard view (tumblr.com/username) that the message window pops up. when i close the blog, the message window disappears as well. messages work normally when i disable tampermonkey.

**Comment by frenchifries** [comment]
now it's working when using the old dashboard layout, but they still won't show up when using the new layout.

**Comment by morphinpink** [comment]
dms don't work for me either :( i don't mind the new layout so i installed this to get avatars back only, i don't want to change everything but dms won't open if i keep the new layout.

**Comment by enchanted-sword** [comment]
Not sure what's causing this, will investigate.

**Comment by morphinpink** [comment]
> 

If it helps reproducing the issue, I'm not using the old dms option on the new layout. I only have the dashboard icons option on with the new layout. For some reason the dms window doesn't pop up.
