### ISSUE TITLE
Blog avatars don't show up on dashboard

### ISSUE THREAD

**Issue by cinnabarlab** [enchanted-sword/dashboard-unfucker#50]
this only started happening today (8/22) and idk if it's something to do with this script or tumblr itself but on my dashboard, the icons of blogs i follow no longer appear to the left of posts like normal. (see attachment)
<img width="1105" alt="Screen Shot 2023-08-22 at 10 12 41 AM" src="https://github.com/enchanted-sword/dashboard-unfucker/assets/51539305/d654bcdf-3e9a-429c-aa39-46f9055aa918">

**Comment by enchanted-sword** [comment]
Already fixed in the latest update

**Comment by cinnabarlab** [comment]
> Already fixed in the latest update

oh my apologies!! ty ^_^
