### ISSUE TITLE
Feature or Bug?

### ISSUE THREAD

**Issue by konamiesque** [enchanted-sword/dashboard-unfucker#51]
I've noticed that sometimes when I or someone else on my dash reblog a post, the username of the person reblogged from doesn't show up in the header of the post. This only really happens when the post is reblogged either directly from the original post or from whoever made the last reblog with text. I can't tell if this is an intentional feature or a glitch, but either way it's a bit buggy, since even if the username doesn't appear, if you aren't following whoever the post was reblogged from, the "Follow" button still shows up.
![Screenshot 2023-08-22 110156](https://github.com/enchanted-sword/dashboard-unfucker/assets/134816792/8f3c2026-b54d-41df-90e5-246dbf32ca71)

**Comment by enchanted-sword** [comment]
This is part of the latest update, haven't had time to fix it yet.

**Comment by enchanted-sword** [comment]
fixed
