### ISSUE TITLE
Gap between "create post" and actual dashboard contents remain even with "hide dashboard tabs" on

### ISSUE THREAD

**Issue by Camwoodstock** [enchanted-sword/dashboard-unfucker#52]
Fairly self-explanatory but um. Just in case, here's an image of the exact thing we're talking about. Checked, and it was not the result of Stylus or some other extension, so... No idea what that's all about?

It's very selective, as sometimes the gap will be present, but sometimes it'll fix itself... And then un-fix itself a few reloads later. Just kinda refresh a bunch and it should crop up eventually.
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/107432951/18c3e437-7161-43e0-9715-a9560e5c5674)

**Comment by enchanted-sword** [comment]
That's probably the carousel container, if you're blocking it with an adblocker you may have missed part of the element. It only shows up sometimes like what you described, and version A doesn't make CSS modifications so I'm not sure what else it would be (shown here with the XKit Rewritten tweak to turn it into a dividing line)
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/5ef5b51a-5fd4-469f-9f3d-4943bb3db44c)
