### ISSUE TITLE
dashboard centered to the far far left

### ISSUE THREAD

**Issue by melmelonmel** [enchanted-sword/dashboard-unfucker#53]
i got the latest update and this happens?? the dash board gets centered to far far left of the screen and a bunch of features get obscured, ive attempted messing with the settings but nothing fixes it other than turning off the dashboard unfucker (picture attached)
![uh oh](https://github.com/enchanted-sword/dashboard-unfucker/assets/142920908/a07c9700-61eb-49a9-b157-1ff14fd6dbee)

**Comment by enchanted-sword** [comment]
Not entirely sure how,  but it's because the version B stylesheet is being applied to the reverted dashboard. Try refreshing or restarting your browser if you haven't already.

**Comment by HyperBeast43** [comment]
make sure you arent running both versions at the same time

**Comment by enchanted-sword** [comment]
Ran into this while debugging, it is indeed caused by running both scripts simultaneously.
