### ISSUE TITLE
Sometimes reblogs just don't show where the reblog came from

### ISSUE THREAD

**Issue by Camwoodstock** [enchanted-sword/dashboard-unfucker#55]
Self-explanatory, and this is a problem tumblr's been having since this morning that someone's probably already brought up ON tumblr, but for the sake of being thorough, uh, have a formal bug report on it.
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/107432951/0d32dfb8-8c69-45e0-b322-c4e5a005eb54)

**Comment by enchanted-sword** [comment]
fixed in 4.1.1b and 3.6.1a
