### ISSUE TITLE
element overlap/off center + own blog icon missing

### ISSUE THREAD

**Issue by SpacedKey** [enchanted-sword/dashboard-unfucker#56]
the "following-for you- your tags- manage..." bar is pushed too far to the right and overlaps with the unfucker menu/ other elements on the right. also my own blog's icon which would be on the left of the new post buttons isn't there
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/109149637/be2c9ef3-e8be-48df-9f6d-8b9414cd2900)

**Comment by enchanted-sword** [comment]
fixed
