### ISSUE TITLE
Inconsistent nav element item removal

### ISSUE THREAD

**Issue by marcustyphoon** [enchanted-sword/dashboard-unfucker#6]
I noticed this line of code:

```js
$nav.children(":nth-child(2),:nth-child(10),:nth-child(11),:nth-child(12)").remove();`
```
Unfortunately, we can't rely on element order here, since (for example) I don't have Tumblr Live muted, so I have an extra button after explore. This means that, for me, this removes the settings menu dropdown, which I assume is unintentional.

I think something like this should work:

```js
$nav.children().has('use[href="#managed-icon__explore"], use["href="#managed-icon__live-video"], use[href="#managed-icon__shop"]', use[href="#managed-icon__earth"]).remove();
```

I can't finish this myself, since I don't have the "get ad-free" icon on my account with the new layout, but I've seen it in screenshots and I assume that's one you probably want to hide!

**Comment by enchanted-sword** [comment]
Tumblr Live isn't in my country, so I always forget it's a thing on desktop. Thanks for pointing that out, this is definitely a neater solution! It also fixes the issue of needing a different set of selectors for the <1150px width layout, which changes the nav icons.

**Comment by enchanted-sword** [comment]
Worth noting: jQuery doesn't seem to support `,` as an AND operator for the selector string in `.has()`, it instead throws a syntax error. I ended up just chaining them together with `.add()`, like such:

`$nav.children().has('use[href="#managed-icon__explore"]').add($nav.children().has('use[href="#managed-icon__shop"]')).add($nav.children().has('use[href="#managed-icon__live-video"]')).add($nav.children().has('use[href="#managed-icon__earth"]')).add($nav.children().has('use[href="#managed-icon__sparkle"]')).remove();`

**Comment by marcustyphoon** [comment]
Oh, strange! Maybe a typo? Mine worked with

```js
$nav.children().has('use[href="#managed-icon__explore"], use[href="#managed-icon__shop"], use[href="#managed-icon__live-video"], use[href="#managed-icon__earth"], use[href="#managed-icon__sparkle"]')
```
