### ISSUE TITLE
extra space on side of dash

### ISSUE THREAD

**Issue by ophiocordyceps** [enchanted-sword/dashboard-unfucker#62]
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/87246648/5296a112-67a9-4448-98c0-bcbd1835983e)

**Comment by enchanted-sword** [comment]
what version is this? i ran into this bug while developing v4.0.0b but i thought i resolved it before pushing the update.

**Comment by ophiocordyceps** [comment]
> what version is this? i ran into this bug while developing v4.0.0b but i thought i resolved it before pushing the update.

late reply whoops. i think all of the bugs i submitted were from the version right after that one

**Comment by enchanted-sword** [comment]
So it no longer occurs in the latest version?
