### ISSUE TITLE
Not working at all, console shows unsafeWindow.tumblr is undefined

### ISSUE THREAD

**Issue by fungaloids** [enchanted-sword/dashboard-unfucker#63]
hey! having some issues with both versions of the script violentmonkey on firefox, i've triple-checked that everything is enabled. i'm getting this in the firefox console:

![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/142951482/2dac942d-4337-4221-b128-edfd6198625e)

not sure if i could have messed anything up through my extensive element removal with ublock origin but i feel like it merits mentioning anyways, along with the fact that i'm running xkit rewritten and tumblr saviour - disabling those did nothing to resolve the situation btw

also thank u for ur hard work in making tumblr.hole functional and not completely stupid :)

**Comment by enchanted-sword** [comment]
what version of firefox are you using? i've had this timeout error happen with violentmonkey, but only in firefox developer and, strangely enough, only on my laptop.

**Comment by vibratoryblurriness** [comment]
I'm seeing the exact same error with Violentmonkey on the current stable version of FF (116) on Linux with a few other extensions, including XKit Rewritten, uBlock Origin and NoScript. No other userscripts that apply to tumblr.com though.

**Comment by fungaloids** [comment]
update: switching from Violentmonkey to Tampermonkey made the script work for me; also, like prev commenter i'm actually also on FF 116 on Linux Mint as well so that might have something to do with what's happening here
