### ISSUE TITLE
profile pics appearing inside post OR overlapping sidebar on new layout

### ISSUE THREAD

**Issue by frenchifries** [enchanted-sword/dashboard-unfucker#64]
i'm sure there's some weird shit going on on tumblr's end that is making this wack out—when using the option to restore profile pics WITHOUT reverting to the old dashboard layout, profile pics appear inside the post instead of next to it.
<img width="855" alt="Screen Shot 2023-08-22 at 9 06 46 PM" src="https://github.com/enchanted-sword/dashboard-unfucker/assets/142453425/ee57863b-22ba-46b9-9c22-5726bc365a84">

if i click the home button after loading the dashboard, they DO appear to the left of posts, but without moving the middle section to the right to accommodate the sidebar, causing an overlap.
<img width="849" alt="Screen Shot 2023-08-22 at 9 12 07 PM" src="https://github.com/enchanted-sword/dashboard-unfucker/assets/142453425/c182282d-184b-4967-b11d-00cfc475af3c">

they DID appear correctly for one brief moment, but i can't seem to replicate whatever i did to make that happen. when using the old dashboard layout, everything looks fine.

**Comment by enchanted-sword** [comment]
this happens because the new layout no longer supports the old avatar style. when i get around to it, i'll make it so disabling the "revert vertical nav layout" toggle also disables this toggle and the messaging ui revert toggle.
