### ISSUE TITLE
Tags page formatting tiny and weird

### ISSUE THREAD

**Issue by mokiwolf** [enchanted-sword/dashboard-unfucker#65]
So this started about 1 week ago(ish) when going to and tracked tag (and even tags that are not tracked)
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/12531509/c827c05a-a504-4e0a-86bc-729b235bc6da)

Everything gets squished down into the tiniest column when before it was... normal.

without the script:
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/12531509/ad87c0d0-2903-4cf2-9997-121de27bedcd)

which is the width it normally is.

116.0.3 (64-bit) of firefox

Thought it might be xkit doing something weird but it still does it with xkit disabled

**Comment by enchanted-sword** [comment]
That is a VERY outdated version of the script, updating should fix that.

**Comment by mokiwolf** [comment]
derp, my bad. updating did indeed fix it! <3 Thanks!
