### ISSUE TITLE
Blog settings page is completely blank

### ISSUE THREAD

**Issue by Samurott1999** [enchanted-sword/dashboard-unfucker#66]
**Bug Description:** When I try to navigate to the blog settings page, I'm getting a blank page instead.

**Behavior reproduction:**
1. Click open the profile menu
2. Click a blog.
3. Click "Blog Settings"
*Important note:* It seems that if you go back, then click Blog Settings again, it works fine. Additionally, it is less likely to be an issue on a main blog; try using a side blog to reproduce this problem.

**Screenshots:**

This is the blog page from step 2:
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/103961169/163a14f0-27e9-4fc2-bb97-c655c5dadad4)

This is the bug in question:
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/103961169/7b3aabc4-8a6a-4f5e-a79c-d922554ea278)

This is what it looks like if you go back and then into the blog settings:
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/103961169/d6e3e7eb-6c79-4cd0-a7f8-0c72b4944cf7)

**Version:**
 - Firefox version 116.0.3 (64-bit)
 - Tampermonkey Version 4.19.0
 - First noticed in Dashboard Unfucker Version 4.1.0b, continues to be a problem in Version 4.1.4b

**Additional context:** This was first noticed while I was trying to set up a new sideblog (not the one pictured).

**Comment by enchanted-sword** [comment]
Hmmm, it seems to be some sort of loading issue, since the script executes fine and the the page layout gets reset (but keeps the stylesheet, which is why everything is hidden). Not sure what needs to be waited on before executing, though.

**Comment by Samurott1999** [comment]
I am curious if there has been any changes made that would be related to this, as there appears to be new, possibly related behavior.
As of Version 4.2.2b, it appears to work fine if you access it from the blog's dropdown in the profile menu. It loads in, appears as the current, "twitter" view for a short time, and then switches to the Dashboard Unfucker version of the blog settings, as seen below.

![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/103961169/f01c64e8-de80-4187-898a-385e280691a7)

However, if you access it from the sidebar menu from viewing your blog's posts, it loads in the "twitter" view and stops loading the Dashboard Unfucker. This appears to be a one time per sideblog per session issue, as I was unable to replicate this for screenshot purposes.
After this one-time issue, it loads with no problem. No brief "twitter" view, and no blank screen.

I am willing to resubmit the one-time bug as a new bug report if it is not related.

**Comment by enchanted-sword** [comment]
Fixed in [this commit](https://github.com/enchanted-sword/dashboard-unfucker/pull/96/commits/f71c50c77796a20ecf198c289bde2253236b8d31)
