### ISSUE TITLE
Using some shortcuts gives an error

### ISSUE THREAD

**Issue by WickyEd** [enchanted-sword/dashboard-unfucker#67]
When using the "Home" shortcut to refresh the dash, and "C" shortcut to make a new post, it gives this error:

![Screenshot 2023-08-23 144129](https://github.com/enchanted-sword/dashboard-unfucker/assets/76656583/fea5930f-d56e-40b7-befd-ead0dba1fc46)

 - Firefox v116.0.3
 - Greasemonkey v4.11
 - Version A v4.1.4

**Comment by enchanted-sword** [comment]
This seems like a permission error with Greasemonkey since it doesn't have access to the same script context. It might be fixable, but in the meantime I would suggest trying Violentmonkey or Tampermonkey.
