### ISSUE TITLE
full width appearance 

### ISSUE THREAD

**Issue by Alucior** [enchanted-sword/dashboard-unfucker#68]
**Describe the bug**
Dashboard is stretched to the full width of the screen when using the dashboard-unfucker, specificcally the unfucker.user.js v3.6.3

**To Reproduce**
1. install the script with tampermonkey
2. reload the dash, or any page on tumblr
3. it appears correct like it was before the update
4. and after a moment it streches to the full with of the browser

**Screenshots**
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/34094715/34f12534-6523-41aa-af4e-1719cf1f4b89)

**Version (please complete the following information):**
 - Browser and version [e.g. FF Nightly 118.0a1]
 - Version [e.g. 3.6.2a]

**Additional context**

**Comment by enchanted-sword** [comment]
That's the XKit Panorama feature, not this script.
