### ISSUE TITLE
Reblog-chain is wrapped into multiple lines on "original reblogs"

### ISSUE THREAD

**Issue by Estecka** [enchanted-sword/dashboard-unfucker#69]
**Describe the bug**
On certain post's headers, the line that indicate who reblogged from who will occasionally be wrapped into multiple lines, instead of a single one.

This does not happen to all reblogs, but it always happens to the same specific posts. The thing that set those posts apart from the others is that they are reblogged directly from an orginal post (including self-reblogs).

The reblogged's name is always the object causing the wrapping. The link on that name is also wrong on affected posts: cliking it will direct me to the post of the reblogger, instead of the reblogged.
For example, in the screenshot below, if I click on "passionpeachy", this will direct me to furblet's blog.

**To Reproduce**
Scroll down you dashboard, and pray you find an affected post.

Presumably it _should_ have been possible to reproduce this by directly reblogging an original post, but for some reason when I tried to do that, the reblogged's name was completely omitted from the header on my own posts. So relying on other peoples doing the reblogging is the only way I've got.

**Screenshots**
![Screenshot_3](https://github.com/enchanted-sword/dashboard-unfucker/assets/39855800/1b45f1d1-7d5a-4ed3-b0c0-4d336d944522)
When inspecting the page's source on the affected posts, I find that the reblogged's name is taking as much horizontal space as possible. This is fixable simply by adding the missing `display: inline` and `margin-right: 5px` to that name.

![Screenshot_4](https://github.com/enchanted-sword/dashboard-unfucker/assets/39855800/7f9b0c4f-5d71-4a0f-907e-65da87bc5105)
Failed attempt at reproducing the bug by reblogging the same post from the source: passionpeachy's name is completely omitted from the header. (The presence of a follow button suggests this absence is also a bug.)

**Version :**
 - Firefox 116.0.3
 - Tampermonkey v4.19.0
 - Dashboard unfucker 3.6.3a

**Comment by enchanted-sword** [comment]
Fixed in v3.6.4a and v4.1.5b
