### ISSUE TITLE
Disabling "add polls to reblogs" breaks polls entirely

### ISSUE THREAD

**Issue by ericvilas** [enchanted-sword/dashboard-unfucker#71]
**Describe the bug**
When using the old UI layout (revert vertical nav layout enabled), if "enable adding polls to reblogs" is disabled, polls break entirely, and don't show up in posts.

**To Reproduce**
1. On your dashboard, locate a post that contains a poll (for instance, by reblogging one)
2. Disable the option of "enable adding polls to reblogs" while keeping "revert vertical nav layout" enabled
3. Refresh the page and scroll to that post
4. The poll doesn't show up, and the post shows up as blank

**Version (please complete the following information):**
 - Google Chrome version 116.0.5845.97
 - Version A, 3.6.3

**Additional context**

**Comment by enchanted-sword** [comment]
Fixed in v3.6.4a
