### ISSUE TITLE
General configuration settings reset after closing browser

### ISSUE THREAD

**Issue by lucasrosenberg** [enchanted-sword/dashboard-unfucker#72]
After closing Firefox all the way and then reopening it, my settings in General Configuration reset. Usually, I keep explore and shop showing. They constantly reset to being hidden for some reason. Every other function works though, so it's not like the regular version of the script isn't working for me (as opposed to the noflags one).

**Comment by enchanted-sword** [comment]
The script uses [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to store the preferences, so they shouldn't reset under normal circumstances. It's possible you might have some setting enabled to either prevent using it or clear it on reload. Try checking out (https://support.mozilla.org/en-US/kb/storage#w_allow-or-block-websites-from-storing-informationl).
