### ISSUE TITLE
Unfuck is not in fact, unfucking my dash

### ISSUE THREAD

**Issue by BBkat13** [enchanted-sword/dashboard-unfucker#73]
**Describe the bug**
It literally just, doesn't work for me? It in fact does the opposite of "unfucking" my dash and made it worse

**To Reproduce**
>clicked 'unfucker.user.js'
>clicked 'raw' and installed it
>opened tumblr

**Screenshots**
My dashboard at current, before applying the 'unfuck my dash'
<img width="829" alt="Screen Shot 2023-08-23 at 4 26 32 PM" src="https://github.com/enchanted-sword/dashboard-unfucker/assets/114542020/17c7db38-0cbb-4612-92c3-e452f1e89af4">

My dashboard AFTER I apply the 'unfuck my dash' script
<img width="823" alt="Screen Shot 2023-08-23 at 4 26 12 PM" src="https://github.com/enchanted-sword/dashboard-unfucker/assets/114542020/e87239ac-dc45-4a94-b085-69cd83767205">

**Version (please complete the following information):**
Firefox ver 116.0.2
On a MacBook Pro (MacOS Monterey, ver 12.6)

the only other things I have installed that affects tumblr is Xkit rewritten (which it claims it works with) and tumblr saviour. So I have no idea why it's, not working, unless it's imcompatible with Macs and no one thought to mention this.

**Comment by BBkat13** [comment]
So it can't be xkit or tumblr saviour b/c I disabled each and refreshed and the problem was still there.

**Comment by TheV360** [comment]
Which extension are you using to install the userscript? I had this problem with Violentmonkey (giving an `unsafeWindow` undefined exception), and I unfortunately had to give up and switch to Tampermonkey. After that, it worked without any further configuration.

Also, maybe open up the developer tools, switch to the Console tab in the tab bar at the top, look for an error from an `eval` source, and post a screenshot of it here. For example, here's an error I caused on purpose for fun (see the `eval:<line number>:<character number>` source in the top right of it):
![](https://github.com/enchanted-sword/dashboard-unfucker/assets/25177071/8121616a-1289-47ec-a2db-f3937e7294d0)

**Comment by BBkat13** [comment]
I'm using Greasemonkey, since I'm on Firefox. 
and where do I find, literally any of that? B/c I'm not seeing any of that for Greasemonkey.

**Comment by TheV360** [comment]
Ah sorry, I was a bit vague about which tab I was talking about. If you enable the userscript, open a new Tumblr tab, and then open developer tools in that Tumblr tab (F12, or right-click somewhere and select Inspect Element), you'll find userscript errors in the Console tab -- and I did have to scroll up a little (past the.. ASCII-art M&M..) to find where the userscript's error was.

Checking just now by installing Greasemonkey, I do have the issue you're describing. Only big difference between Tampermonkey and Greasemonkey is that for Greasemonkey, the console error box's "Source" label shows `sandbox eval code` instead.
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/25177071/ffae2699-c658-4feb-8c8c-18d26cff94af)

(Oh, there's two unrelated errors above the real one... The small red "`eval` code" error box on the bottom is the only thing that matters, though.)

**Comment by enchanted-sword** [comment]
Greasemonkey tends to run into problems with the injection context, I've had it work for me before, but it doesn't seem to work for most people so I think I'm going to just remove it from the compatibility list. Violentmonkey is more reliable, but it seems to timeout sometimes when fetching the window helpers, so my first and foremost recommendation is to use Tampermonkey.

**Comment by BBkat13** [comment]
Eyyye it works on Tampermonkey! 
I guess it just did not like Greasemonkey.
