### ISSUE TITLE
Selecting "Raw" does not install the script

### ISSUE THREAD

**Issue by VeloJello** [enchanted-sword/dashboard-unfucker#77]
As the ReadMe instructs, I open the following:

https://github.com/enchanted-sword/dashboard-unfucker/blob/main/unfucker.js

And click the "Raw" button. A page opens with the following text:

//filename was changed: go to https://github.com/enchanted-sword/dashboard-unfucker, select the version you want, and hit the "raw" button with tampermonkey installed to install the script

Nothing else happens, though. I have Tampermonkey installed and am using Firefox.

**Comment by enchanted-sword** [comment]
`unfucker.js` is just a redirect since the script name was changed. Go to (https://github.com/enchanted-sword/dashboard-unfucker/raw/main/unfucker.js) instead.

**Comment by VeloJello** [comment]
> `unfucker.js` is just a redirect since the script name was changed. Go to (https://github.com/enchanted-sword/dashboard-unfucker/raw/main/unfucker.user.js) instead.

I was hoping that that wasn't the right one. It installs, but the dashboard is extremely wide. Is it meant to be this wide? Is it possible to make it less wide?
![wide](https://github.com/enchanted-sword/dashboard-unfucker/assets/25390850/20d8388a-ae0a-457d-8cb3-ade8800af132)

**Comment by enchanted-sword** [comment]
That's the XKit Panorama feature.
