### ISSUE TITLE
Entire dashboard is shifting to left after returning from minimizing page or refershing page ;((

### ISSUE THREAD

**Issue by octonusm9000** [enchanted-sword/dashboard-unfucker#79]
**Describe the bug**

**To Reproduce**

**Screenshots**
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/142871971/62f8ecdf-c4b2-4438-a78c-843c4e98be9a)

**Version (please complete the following information):**
 - Browser and version [e.g. FF Nightly 118.0a1]
 - Version [e.g. 3.6.2a]

**Additional context**

**Comment by enchanted-sword** [comment]
This issue is caused by having two versions of the script active at once, which can happen when updating from an old version. Go to you your active scripts list and disable the older one.

**Comment by octonusm9000** [comment]
my apologies...how do I do this?

**Comment by enchanted-sword** [comment]
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/66f39f27-a59f-40a3-9da3-220bc5b02eb5)
The name will probably be different, but there should be two, and you can click on each one and hit "edit" to view the version. You can then disable whichever one is older.

**Comment by octonusm9000** [comment]
hi, I can't log into my github account...the latest and greatest dashboard
unfucker ain't working so hot
[image: image.png]

**Comment by enchanted-sword** [comment]
Had a weird issue unique to tampermonkey, should be fixed now.

**Comment by octonusm9000** [comment]
heck yeah...worked...you are a lifesaver and I really appreciate you
