### ISSUE TITLE
Option to show dashboard tab bar

### ISSUE THREAD

**Issue by marcustyphoon** [enchanted-sword/dashboard-unfucker#8]
For users with accounts new enough to have the "for you" tab as the default (i.e. those made after May 8th, 2023), it's pretty important to be able to access the "following" tab to actually be able to use your dash, so while I don't really know how to do options in a user script it seems important to allow that particular element hide to be disabled in some way!

(Also, I personally use it for the "blog subs" tab, so even though I don't have a new account it's a must have for me.)

**Comment by enchanted-sword** [comment]
I might see if I can make options in the future, but for now I unhid it and set the following tab the default for new accounts.
