### ISSUE TITLE
dash unfucker not working on mac

### ISSUE THREAD

**Issue by silver9mm** [enchanted-sword/dashboard-unfucker#83]
**Describe the bug**

Earlier today I successfully installed tampermonkey and dash unfucker for tumblr dash on my HP laptop. Works great. Tried to follow the same steps for husbands Mac and it would not work. I cleared the cache, open and closed the browser, turned off AdBlock, allowed permission in the extension details for tampermonkey, installed firefox and repeated all the steps, made it so you didn't have to 'click to allow', uninstalled new xkit and installed xkit rewritten, and I can't get it to work.

**To Reproduce**

**Screenshots**

**Version (please complete the following information):**
 - Browser and version [e.g. FF Nightly 118.0a1]
 - Version [e.g. 3.6.2a]

**Additional context**

**Comment by enchanted-sword** [comment]
What version are you using? And what exactly do you mean by not working? Does it fail to inject at all, or stop partway through?

**Comment by silver9mm** [comment]
v3.6.4
and by not working, i mean it does nothing on the mac laptop. I can download tampermonkey and see it in the extensions,  I can put the script into tampermonkey where it says "put your code here" and when I open/close the browser, refresh and clear cache and make sure allowances that i know of are turned on, nothing happens, tumblr looks fucked still. I tried it on Chrome and Firefox on the Mac, neither would unfuck the dash. I did it on my HP laptop this morning and it unfucked the dash, but this afternoon when I tried on the Mac, it wouldn't unfuck the dash. We just opened it again this second and still fucked.




________________________________

**Comment by enchanted-sword** [comment]
I would imagine you've already checked this, but just make sure both Tampermonkey and the script are enabled on the page:
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/186c517d-dda8-47fb-89d5-c311e04211c3)
And after that, check the browser console (F12 => Console) and see if there are any errors thrown by the script:
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/88f2a141-0f29-4ef8-97d3-b923250e77c1)

**Comment by enchanted-sword** [comment]
It sounds like you put the code inside the default code instead of replacing it. Delete the entire contents of the code editor, and THEN paste in the code, like such:
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/9a11eb9b-e5a8-426e-8c2a-431f0b207c96)
Alternatively, install the script by clicking on [this link](https://raw.githubusercontent.com/enchanted-sword/dashboard-unfucker/main/unfucker.user.js).
