### ISSUE TITLE
Gap between top of page and search bar

### ISSUE THREAD

**Issue by firebird4666** [enchanted-sword/dashboard-unfucker#84]
**Describe the bug**
Not sure if this is a bug or a feature, but there is a large gap between the search bar and top of the web page.

**To Reproduce**
Happens with every reload.

**Screenshots**
Not very tech savy, couldn't figure out a way to link an image :( 
Gap is the same height as the search bar

**Version (please complete the following information):**
 - Browser and version: Firefox 116.0.3
 - 3.6.4a

**Additional context**
If it's a feature I'd love for the option to turn it off, it takes up a lot of the screen while scrolling.

**Comment by enchanted-sword** [comment]
This is a bug; I've never encountered this myself oddly enough, but everyone who has has told me that it fixes itself after you search something in the searchbar.

**Comment by firebird4666** [comment]
Gotcha, thanks!
