### ISSUE TITLE
avatars not appearing after scrolling down through 7 posts

### ISSUE THREAD

**Issue by BarryAllen2024** [enchanted-sword/dashboard-unfucker#85]
**Describe the bug**
What the title says. After scrolling down 7 (that was what it was for now, I counted) posts, the avatars disappear

**To Reproduce**
1. Open Tumblr
2. Scroll down about that many posts

**Screenshots**
<img width="680" alt="Screenshot 2023-08-24 at 11 12 33 PM" src="https://github.com/enchanted-sword/dashboard-unfucker/assets/103613503/00c337b9-54a9-4f6c-a3cb-54217a8f0b46">

**Version (please complete the following information):**
 - Browser and version: Firefox 116.0.3
 - Version: v4.1.7b

**Comment by BarryAllen2024** [comment]
Okaayyyy I retract this slightly. For the post above in the screenshot by prisonhannibal and then another post below it, there were no avatars, but there were avatars for all the other posts below it. Will update if anything changes.

**Comment by enchanted-sword** [comment]
Is it only present on non-reblogged posts? (where you're following the OP) Also, if you just recently updated, I would try refreshing a few times, it works fine for me but I had to reload it a few times while debugging.

**Comment by BarryAllen2024** [comment]
Okay it appears that updating the code has fixed everything. Ty!!
