### ISSUE TITLE
insanely funny bug - loading dots are images of my avatar instead

### ISSUE THREAD

**Issue by BarryAllen2024** [enchanted-sword/dashboard-unfucker#86]
**Describe the bug**
When I scroll down in infinite scroll and wait for the page to load more posts, instead of three gray boxes shrinking and unshrinking, it's images of my avatar instead.

**To Reproduce**
1. Scroll on infinite scroll until more posts need to load, preferably fast and forcing the page to load as many posts as possible (it's how I noticed it)

**Screenshots**
<img width="625" alt="Screenshot 2023-08-24 at 11 51 05 PM" src="https://github.com/enchanted-sword/dashboard-unfucker/assets/103613503/033df93e-0e85-49e5-af5b-f565b5163f40">

**Version (please complete the following information):**
 - Browser and version: Firefox 116.0.3
 - Version: v4.1.7b

Could be an xkit glitch but I don't think so.

**Comment by enchanted-sword** [comment]
It appears the loading dots use the same class as the bar at the top of the timeline, so it was appending the icon to those when they popped up. 
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/11c2ca2c-6109-47af-92a6-686788c51c1b)
This should be fixed in v4.2.0.
