### ISSUE TITLE
avatars appearing inside top of posts instead of beside

### ISSUE THREAD

**Issue by pandoranmama** [enchanted-sword/dashboard-unfucker#87]
**Describe the bug**
> Avatars appear in the top of the posts instead of beside them.
> They appear normally for a moment when switching between the "for you", "following", etc tabs, but refreshing the page manually puts them back into the top of the post.
> 
> Refreshing, clearing history, uninstalling and reinstalling the script and opening and closing the browser does not fix it.

**To Reproduce**
> The only thing I have done is install the script with the tampermonkey extension.

**Screenshots**
> If applicable, add screenshots to help explain your problem.
> ![d2a4ef3b1e390c74c8f4b83360388281](https://github.com/enchanted-sword/dashboard-unfucker/assets/143178558/62da1660-275c-4640-963a-3e00562befa7)
>
>![37c9bc2ae6f1051dab1b210afdffb482](https://github.com/enchanted-sword/dashboard-unfucker/assets/143178558/d01bd9e4-5cb1-437d-b45d-4e83c5654299)

**Version (please complete the following information):**
 - Version 116.0.3 (64-bit)
 - unfucker.user.js 3.6.5

**Additional context**
>It only happens to the first four or so posts on the dashboard before the avatars show normally.
>This is only happening on this new tumblr account I made a day or so ago — the dash did not even have the vertical layout like they have been changing the dashboards to. The icons work fine on my main account in a different firefox window/profile, so not connected to this one.

**Comment by enchanted-sword** [comment]
Weird, version A modifies the avatars solely by disabling the new avatar update, so how style bugs would be present is beyond me. I wasn't able to replicate this on a new account, although it's strange that you mention it not having the vertical nav update.

**Comment by pandoranmama** [comment]
I'm honestly confused as well, but the dashboard was just the layout it was before the update when I made this new account, minus the avatars, and I honestly don't know why. The only extensions I have that affect tumblr are the xkit rewritten, and the time I tried this one. All other extensions I have are also on the window/profile of my main account and don't affect anything to do with it.

---
The new accounts dash showing that the extension is off VS main blog with it off

![b2208791af3befb9c49b5de89ee4ef1c](https://github.com/enchanted-sword/dashboard-unfucker/assets/143178558/a74e8025-e517-4714-a66e-d390395aa5f4)

![279e42f1df8d5ef45d13500f3b05c329](https://github.com/enchanted-sword/dashboard-unfucker/assets/143178558/0fabe4da-cd13-4105-906f-eb5596607113)

---
And then with the extension on

![b789c7ad9442b87a66f391608aff15ae](https://github.com/enchanted-sword/dashboard-unfucker/assets/143178558/4ab37257-6289-472f-8df1-b9aea99b52a2)

![dd54695d9a02c251db2503fea5d63476](https://github.com/enchanted-sword/dashboard-unfucker/assets/143178558/018cd72b-6c9a-410e-84b6-4bb7771156c1)

**Comment by enchanted-sword** [comment]
Can you send a screenshot of the inspector focused on the "AD_w7" element on one of the affected posts? (Like such)
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/b7e16397-df0f-44a5-a1ae-3c24e6e7955f)

**Comment by pandoranmama** [comment]
While the page itself seems to have that, trying to focus on it when it comes to the affected posts does not have the "AD_w7" at all, even when searched for.

![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/143178558/4c2fcea0-e26b-4a99-aded-468d7a7a0ed6)

![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/143178558/4616d631-9511-4703-85b6-52f3305c6ea2)

---
And now Luffy has joined my tabs??? LOL
Probably tumblr being tumblr, but that caught me off guard while I was taking screenshots.

**Comment by enchanted-sword** [comment]
That is really weird. Version A doesn't make any modifications to the post header aside from adding missing names, so it seems like the elements created by Tumblr itself are set up as the mini-avatars that appear in reblogs inside the trail instead of the larger sticky avatar that appears alongside the posts. I still haven't been able to replicate this, but I might be able to include a failsafe that checks the first posts loaded for this bug.
