### ISSUE TITLE
radar toggle not working?

### ISSUE THREAD

**Issue by maltsea** [enchanted-sword/dashboard-unfucker#88]
Radar is showing up despite the setting to disable it being ticked. Refreshed the page normally, and did f5 as well and it's still there. Tried to refresh both while it was on, and off as well, no change. Tried to update in case there was an issue that was fixed, which there wasn't an update. 
Very minor, overall, but annoying.

![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/60683032/a087f7b9-59af-47a1-b8ea-2720fdd9e1d0)
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/60683032/3ea067d5-8498-4368-a3df-7d2c5bdd389f)

My browser version of Vivaldi is 6.1.3035.302.

**Comment by enchanted-sword** [comment]
Two ideas that come to mind;
1. The script doesn't explicitly hide the radar, it rather toggles it, so if it was already hidden it would show it instead. This might be the case if you have something like XKit or an adblocker also disabling the radar.
2. In some cases, I have seen the recommended blogs take longer to load than other items on the page, and the script currently takes this into account by processing it asynchronously, but it's possible this could extend to the radar as well. if my first idea isn't the case, if it isn't too much difficulty could try you inserting the line `;;debugger;` into the script like such:
![image](https://github.com/enchanted-sword/dashboard-unfucker/assets/81981111/9cfb37d3-b916-43c6-86b7-e19350ee637d)
and then reloading tumblr, opening the console while the page is frozen in the debugger state, and entering `$(".FZkjV").has(".KU8aS")` and commenting the response here?

**Comment by enchanted-sword** [comment]
Forgot the radar can show up on non-dashboard pages, should be fixed for good now.
