### ISSUE TITLE
Reblogs don't work

### ISSUE THREAD

**Issue by Ashlyn9** [enchanted-sword/dashboard-unfucker#89]
**Describe the bug**
When I try to reblog any post it immediately loads an error screen. 

**To Reproduce**
Pick a post. 
Press the reblog button

**Screenshots**

![Screenshot (137)](https://github.com/enchanted-sword/dashboard-unfucker/assets/143218296/a9519558-59ca-4092-9e3c-f64cf87d0b41)
**Version (please complete the following information):**
 - Firefox Version 116.0.3 (64-bit)
 

**Additional context**

**Comment by enchanted-sword** [comment]
What script injector are you using?

**Comment by Ashlyn9** [comment]
Tampermonkey BETA

**Comment by enchanted-sword** [comment]
Not 100% sure why but I ran into the same issue when trying Beta, using the regular version should fix this
