### ISSUE TITLE
With paged (not infinite scroll) next page results in a javascript error

### ISSUE THREAD

**Issue by mjharwood** [enchanted-sword/dashboard-unfucker#90]
**Describe the bug**

Next page results in an error requiring a page reload every time.

**To Reproduce**
Disable infinite scroll.
Click the next page button (or right arrow key)
Page displays an error.
Reloading the page displays successfully.

**Screenshots**
Page returns

Unexpected Application Error!
Permission denied to access object

21669/tY/<@https://assets.tumblr.com/pop/js/modern/main-d27df78b.js:87:639
21669/tX/<@https://assets.tumblr.com/pop/js/modern/main-d27df78b.js:87:3528
46306/n/<@https://assets.tumblr.com/pop/js/modern/main-d27df78b.js:129:330518
sn@https://assets.tumblr.com/pop/js/modern/vendor-227e1cff.js:22:96138
...

**Version (please complete the following information):**
 - FireFox 116.0.1
 - Version 4.1.7

**Comment by enchanted-sword** [comment]
What script injector are you using?

**Comment by mjharwood** [comment]
Greasemonkey

**Comment by enchanted-sword** [comment]
Switching to Tampermonkey should fix this.
