### ISSUE TITLE
Some Reblogs Are Missing Who it was Reblogged From

### ISSUE THREAD

**Issue by Avakining** [enchanted-sword/dashboard-unfucker#91]
**Describe the bug**
Some (not all) reblogs are missing who it was reblogged from

**To Reproduce**
1. Go to the dashboard or a post URL such as [this one](https://www.tumblr.com/allodyniaangel/726670918159663104)
2. Look at the post's header
3. It's missing who it was reblogged from

**Screenshots**
<img width="535" alt="Screenshot 2023-08-25 at 20 00 05" src="https://github.com/enchanted-sword/dashboard-unfucker/assets/25210618/854b0a18-1b06-4b8c-ad42-0f60e7befcdf">

**Version (please complete the following information):**
 - Browser and version: Firefox 116.0.3
 - Version: 3.6.5a

**Additional context**
This shouldn't matter but I'm on macOS 13.5.1

**Comment by enchanted-sword** [comment]
This should be fixed on the dashboard page, but permalink pages present an interesting conundrum since they don't allow for pathname-based filtering to determine whether it is a page that should run the observer or not. Will look into this.
