### ISSUE TITLE
A "Disable Badges" option

### ISSUE THREAD

**Issue by LadyHaywood** [enchanted-sword/dashboard-unfucker#97]
**Describe the feature:**
Being able to disable badges from beside users' names.

**Comment by enchanted-sword** [comment]
added in the v4.0.0 beta

**Comment by LadyHaywood** [comment]
Cool! How do I change over to the beta?

**Comment by enchanted-sword** [comment]
https://github.com/enchanted-sword/dashboard-unfucker/raw/gen4/unfucker.user.js
