### ISSUE TITLE
An option to make dashboard posts wider?

### ISSUE THREAD

**Issue by JustDownloadin** [enchanted-sword/dashboard-unfucker#98]
Would it be possible to add a toggle or a slider to make the contents of the dashboard wider? Something like Xkit's Panorama (though not as extreme); I used to have a userstyle that did that, but something on tumblr's backend changed and I haven't figured out a way to do it through just CSS. Would it be possible to make it a thing with this script? Thanks

**Comment by enchanted-sword** [comment]
It would certainly be possible. Eventually, I might re-add the deprecated content positioning feature and combine it with something like that to allow repositioning and resizing the timeline; whether or not it makes it into my current PR depends on how much still needs to be done for my current projects, but as of right now it's looking like smooth sailing. You could also open a feature request over at https://github.com/AprilSylph/XKit-Rewritten for an option to change the panorama effect's relative width. I doubt XKit would end up implementing it before I would, but it's still good feedback, and it's possible other XKit users would be interested in having that option.

**Comment by enchanted-sword** [comment]
Actually, it's already a draft PR in XKit: https://github.com/AprilSylph/XKit-Rewritten/pull/845. AFAIK though panorama might still be broken with the vertical nav layout enabled, so might be a while before it's updated.

**Comment by enchanted-sword** [comment]
The feature is now live in v4.0.4beta

**Comment by JustDownloadin** [comment]
> The feature is now live in v4.0.4beta

Thank you! It works like a charm <3

**Comment by JustDownloadin** [comment]
> The feature is now live in v4.0.4beta

Thank you! It works like a charm <3
