### ISSUE TITLE
Unfucker isn't working at all?

### ISSUE THREAD

**Issue by githubguyyyy** [enchanted-sword/dashboard-unfucker#99]
It doesn't even look like it's installed when I open tumblr. I tried turning off all my extensions and confirming tampermonkey is still working? I'm on firefox btw

**Comment by enchanted-sword** [comment]
Version? Script injector?

**Comment by gnollhide** [comment]
I can second this, I was using 4.0.0 with tampermonkey 4.19.0 on firefox 102.14.0esr, it didn't appear to be working at all. I thought maybe something was broken (I was using unfucker.user.js if that matters) and tried downgrading back to 3.6.6 and it worked as expected.

**Comment by gnollhide** [comment]
Version 4.0.2beta seems to work perfectly and has no problems, I'll go ahead and reinstall 4.0.0beta and test to see which lines were causing trouble

**Comment by enchanted-sword** [comment]
I think that popup normally appears every time you load tumblr for the first time with an adblocker enabled. I haven't be able to replicate it consistently, but occasionally when opening a new tab or restarting my browser the script doesn't get injected by the extension. Not sure if this is the same issue here, but I'm not sure how to fix it considering it seems to be the extension just not working when the page first loads.

**Comment by enchanted-sword** [comment]
Nevermind, I forgot this was an issue I have literally already encountered with the script and I already fixed inside the injected script: The script can execute BEFORE `<head>` is loaded. I thought the extension wasn't injecting because it wouldn't pause for a debugger statement at the head of the script, but I think that is just be a document load thing where it can't pause for the debugger statement before a certain point.

**Comment by gnollhide** [comment]
Yeah I managed to grab the console output this time when it happened, and it was indeed on the first time loading Tumblr for today. Here's the full console output https://pastebin.com/fCqDD2rQ but unfortunately I didn't actually see any errors or warnings being thrown into the console.

**Comment by gnollhide** [comment]
That and simply refreshing the page seemed to cause it to once again work perfectly, which does sound like it's being injected too early.

**Comment by Saraiguma** [comment]
I've also not been able to make it work, the console spits the following errors on load:


[tumblrerrror.txt](https://github.com/enchanted-sword/dashboard-unfucker/files/12491105/tumblrerrror.txt)

the only relevant add-ons I have (firefox) are xkit rewritten, shinigami eyes, and violentmonkey (which I am using the run this script)

**Comment by enchanted-sword** [comment]
@e-t-l @Saraiguma v3.6.6a doesn't support Violetmonkey, but [v4.0.0 onwards](https://github.com/enchanted-sword/dashboard-unfucker/blob/gen4/unfucker.user.js) does.
